modify phalcon/mvc/model/metadata/redis.zep, __construct, add share r…
phalcon/cphalcon pull request #11730
Opened 2016-05-02 04:32 UTC by slilin

when  i use session, modelsCache and modelsMetadata service, i found phalcon create multi redis handle;
redis of session use Backend redis handle, but redis of metadata create a new instance in construct, can't use exist reids. so i modify phalcon/mvc/model/metadata/redis.zep:
  
> if \Phalcon\Cache\Backend\Redis handle exist in options, use it, 
   if not exist, it create a new one.

2016-05-02 06:00 UTC, slilin commented
add identify of optiosn["redis"]

2016-05-31 17:34 UTC, sergeyklay commented on phalcon/mvc/model/metadata/redis.zep
> +		if isset options["redis"] && options["redis"] instanceof Redis {
I prefer something like this:
```zephir
use use Phalcon\Cache\Backend\Redis as RedisBackend;

var redis;

if fetch redis, myArray["redis"] && typeof redis == "object" && redis instanceof RedisBackend {
    // ...
} else {
   let redis = ...
}

let this->_redis = redis;
```

2017-05-23 06:12 UTC, sergeyklay requested changes
I think this PR should be more accurate. For example, metadata adapter can get a service instead of injecting a dependency through a constructor. Or user can pass service name instead instance of redis backend

2017-10-03 21:30 UTC, sergeyklay commented
I'm closing this PR due to the lack of any reaction.  If there are real needs, we can consider this in new PR.

2017-10-03 21:30 UTC, closed without merging