Update unit test for prepend/ append/ getTitle
phalcon/cphalcon pull request #12236
Opened 2016-09-19 20:05 UTC by butamuh4o

Update tests for prependTitle and appendTitle functions.
For details:  #12233 

Update test for setTitle and getTitle: Make sure that getTitle(false) did not return <title> tag element

2016-09-19 20:07 UTC, butamuh4o commented
Hope i make it right now. Sorry for my mistakes :/

2016-09-19 20:10 UTC, sergeyklay approved these changes

2016-09-19 20:53 UTC, virgofx commented
Unit tests look fine ... can we get can update though for the actual Tag implementation so this will pass?

2016-09-19 21:12 UTC, butamuh4o commented
@virgofx i will try to make this changes too...

2016-09-19 23:34 UTC, sergeyklay commented
@butamuh4o As you can see tests fails

2016-09-20 04:38 UTC, butamuh4o commented
@sergeyklay I want to ask you to help me with something about a change i was trying to do. Can u check that and give me some details where and what is wrong with syntax? Thank you!!!

```
	/**
	 * Prepends a text to current document title
	 */
	public static function prependTitle(var title) -> void
	{
		var prepend = [];
		if self::_documentPrependTitle !== null {
			let prepend = self::_documentPrependTitle ;
		}
		
		if typeof title == array {
			let prepend = title;
		} else {
			if typeof title == string {
				array_unshift(prepend, title) ;
			}
		}
		
		if !empty prepend {
			let self::_documentPrependTitle = prepend ;
		}
	}
```

2016-09-20 05:49 UTC, sergeyklay commented on phalcon/tag.zep
> +		if typeof title == "array" {
This is new feature request?

2016-09-20 05:54 UTC, sergeyklay commented on phalcon/tag.zep
> +		let self::_documentPrependTitle = prepend ;
So now `_documentPrependTitle` is array or null and this breaking BC

2016-09-20 05:54 UTC, sergeyklay requested changes

2016-09-20 05:57 UTC, butamuh4o commented
No it is not change request. Just think it is better to have that option. Will revert that idea. Sorry

2016-09-20 05:59 UTC, sergeyklay commented
It is good idea, but for 3.1.x not for 3.0.x

2016-09-20 06:04 UTC, closed without merging

2016-09-20 06:06 UTC, sergeyklay commented
@butamuh4o Also could you update CHANGELOG.md?

2016-09-20 06:12 UTC, butamuh4o commented
So i will make a clear pull request and update changelog. Just to get to the office. Thank you!