Added two new filters for use in the Filter->sanitization() method.  …
phalcon/cphalcon pull request #12243
Opened 2016-09-21 20:41 UTC by jabarihunt

Added two new filters for use in the Filter->_sanitization()_ method...

The first is FILTER_BOOLEAN, which returns the boolean value (true or false) if the value is an actual boolean (not 0, 1, 'true' as a string, etc) or it returns null if the value is not a true boolean.

The second is FILTER_BOOLEAN_CAST, which returns whatever the boolean would be of the casted value.  For example, 1 would return true and and empty string would return false.

**_NOTE:_** FILTER_BOOLEAN is a special case that required a break in the sanitization switch statement since it may return null.  This was accounted for in related loops.

2016-09-21 21:52 UTC, sergeyklay commented on phalcon/filter.zep
> +				return is_bool($value) ? $value : null;
`$value` or `value` ?

2016-09-21 21:53 UTC, sergeyklay commented on phalcon/filter.zep
> +					if (value === null) {break;}
parentheses not needed here

2016-09-21 21:53 UTC, sergeyklay requested changes

2016-09-22 01:42 UTC, jabarihunt commented on phalcon/filter.zep
> +				return is_bool($value) ? $value : null;
Not sure what you are asking here.  Would you rather I use an if statement instead of the ternary operator?

2016-09-22 01:50 UTC, jabarihunt commented on phalcon/filter.zep
> +					if (value === null) {break;}
I changed the syntax in the last commit.

2016-09-22 05:44 UTC, sergeyklay commented on phalcon/filter.zep
> +				return is_bool($value) ? $value : null;
I meant that you should use `value` without `$`

2016-09-22 05:44 UTC, sergeyklay commented on phalcon/filter.zep
> +
```
return boolval(value);
```

2016-09-22 14:40 UTC, andrew-demb commented
These changes it's new features. By semver it must be in new minor version, not 3.0.x. Maybe need to create branch 3.1.x and move PR to new branch?

2016-09-22 15:07 UTC, Jurigag commented
Well most of PRs need to be redone on 3.1.x.

2016-09-22 15:07 UTC, Jurigag reviewed
This is new feature and need 3.1.0 label.

2016-09-22 19:07 UTC, jabarihunt commented on phalcon/filter.zep
> +				return is_bool($value) ? $value : null;
Corrected!  Sorry, I was stuck in PHP mode.

2016-09-22 19:23 UTC, sergeyklay commented
@jabarihunt Could you please rebase onto 3.0.x and update CHANGELOG.md. Also squash commits so it would contain only 1 commit.

2016-09-22 19:28 UTC, jabarihunt commented on phalcon/filter.zep
> +
Corrected.

2016-09-30 06:23 UTC, sergeyklay commented on phalcon/filter.zep
> +<<<<<<< HEAD
Could you please resolve conflicts?

2016-09-30 06:26 UTC, sergeyklay commented
@jabarihunt 
Thank you for contributing.
Could you please cover new feature by small unit test?

2016-09-30 06:40 UTC, Jurigag commented
Also squash please.

2016-12-11 19:39 UTC, sergeyklay commented
@jabarihunt Could you please rebase onto 3.1.x ?

2017-04-26 09:53 UTC, sergeyklay commented
@jabarihunt Could you please rebase onto 3.2.x ?

2017-12-13 22:09 UTC, closed without merging