Mvc\Model\Manger::executeQuery() is now more succinct
phalcon/cphalcon pull request #12297
Opened 2016-10-07 10:29 UTC by SidRoberts

`createQuery()` is the method immediately above it and it uses the same code. :stuck_out_tongue_closed_eyes:

2016-10-07 12:25 UTC, sergeyklay requested changes

2016-10-07 12:25 UTC, sergeyklay commented on phalcon/mvc/model/manager.zep
> +		let query = this->createQuery(phql);
How about `_lastQuery `?

2016-10-07 12:34 UTC, SidRoberts commented on phalcon/mvc/model/manager.zep
> +		let query = this->createQuery(phql);
It's on line [1709](https://github.com/phalcon/cphalcon/pull/12297/files#diff-8212f6f15cd92872f55e7d0e66172601L1709)

2016-10-07 15:25 UTC, sergeyklay commented on phalcon/mvc/model/manager.zep
> +		let query = this->createQuery(phql);
👍

2016-10-07 15:25 UTC, sergeyklay approved these changes

2016-10-14 12:16 UTC, sergeyklay commented
@SidRoberts Could you please rebase

2016-10-14 12:50 UTC, merged

2016-10-14 12:50 UTC, sergeyklay commented
Thanks