[RFC] Converting Active Record to the Data Mapper pattern
phalcon/cphalcon pull request #12317
Opened 2016-10-14 09:30 UTC by SidRoberts

So I thought I'd have a go at converting Phalcon's Active Record models to the Data Mapper pattern (see [Doctrine](http://www.doctrine-project.org/projects/orm.html)) and I want to hear people's thoughts and opinions before I take it any further.

I've avoided doing to much work just in case it ends up being a dead-end so no code has been refactored and methods in the models manager now call protected methods in Phalcon\Mvc\Model, etc; - it's a bit of a mess. Obviously this will/should all change.

Put succinctly, methods have been moved to the models manager and (currently) operate exactly as they did before:

```php
// Before
$person = People::findFirst($params);

// After
$person = $modelsManager->findFirst(
    People::class,
    $params
);
```

```php
// Before
$person = People::count($params);

// After
$person = $modelsManager->count(
    People::class,
    $params
);
```

```php
// Before
$person->delete();

// After
$modelsManager->delete($person);
```

```php
// Before
$person->save($params);

// After
$modelsManager->save($person, $params);
```

Phalcon\Mvc\Model is still far too complicated, in my opinion, so there's still a lot of work to do. :stuck_out_tongue: 

A few things that I'd like to do is remove the ability to assign properties during create/update/save:

```php
$robot->save(
    [
        "name" => "Bender",
    ]
);

$modelsManager->save(
    $robot,
    [
        "name" => "Bender",
    ]
);
```

I know people like it because it acts a little shortcut but it doesn't make sense in the data mapper context and looks a little clumsy. A method called `save()` should save and do nothing else.

I'd also like to decide between only supporting [public properties or getters/setters](https://docs.phalconphp.com/en/latest/reference/models.html#public-properties-vs-setters-getters) but have no personal preference of either. Alternatively (or additionally), make an effort to vastly simplify how properties are get/set internally.

(It goes without saying but is obviously aimed at version 4 - not version 3)

Thoughts?

2016-10-14 09:37 UTC, Jurigag commented
Intorduce pls repository class imho as well, because using modelsManager is dirty. So we can still jus t do `$personRepostory->find();` for example.

Also this change is of course for 4.0.0. I thought @andresgutierrez was planning this for 4.0.0

2016-10-14 12:34 UTC, sergeyklay approved these changes
Looks great to me

2016-10-14 13:15 UTC, Green-Cat commented on phalcon/mvc/model/manager.zep
> +
Too much spacing.

2016-10-14 13:17 UTC, Green-Cat commented on phalcon/mvc/model/manager.zep
> +	 * Allows to query the first record that match the specified conditions
Allows to query for the first record that matches the specified conditions

2016-10-14 13:32 UTC, SidRoberts commented on phalcon/mvc/model/manager.zep
> +
I was going for speed. :wink:

2016-10-14 13:34 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +
No need for speed, it will be at least few months until we create 4.0.x repo i guess, and few years to release :D

2016-10-14 15:46 UTC, SidRoberts commented
@Jurigag, it'd be tedious to have to create repository classes for each model. We could set the model class name in the constructor though:

```zephir
namespace Phalcon\Mvc\Model;

class Repository
{
	public function __construct(string! modelClass);

	public function find(array params = []) -> <ResultsetInterface>;

	public function findFirst(array params = []) -> <ModelInterface>;

	public function count(array parameters = []) -> int;

	public function sum(array parameters = []);

	public function maximum(array parameters = []);

	public function minimum(array parameters = []);

	public function average(array parameters = []);
}
```

It would reduce the complexity of the Models Manager a bit but would repositories add complexity for  users/developers?:

```php
$robots = $modelsManager->findFirst(
    Robots::class,
    $params
);

// OR ...

$robotsRepository = $modelsManager->getRepository(
    Robots::class
);

$robots = $robotsRepository->findFirst($params);
```

2016-10-14 15:51 UTC, SidRoberts commented on phalcon/mvc/model/manager.zep
> +	 * Allows to query the first record that match the specified conditions
Fixed in 77acbfe.

2016-10-14 16:22 UTC, Jurigag commented
I mean if you don't want - you don't need to create repository. You can use as well just `$modelsManager->findFirst(Robots::class, $params)` i guess maybe. Repository will be just some kind of shorthand and some place where you can add addtional methods for finding stuff. I know developer can always create his own method but in most Data Mappers there is Repository class introduced.

2016-10-14 16:37 UTC, Jurigag requested changes
`Phalcon/Mvc/Model/Repository` class, add option to use custom Repository class for models.

2016-10-14 16:43 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +			if model->_preSaveRelatedRecords(writeConnection, related) === false {
There should be something like `Phalcon\Mvc\Model\Worker` or `Phalcon\Mvc\Model\UnitOfWork` which will do this.

2016-10-14 16:44 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +			let success = model->_doLowUpdate(metaData, writeConnection, table);
There should be something like `Phalcon\Mvc\Model\Worker` or `Phalcon\Mvc\Model\UnitOfWork` which will do this.

2016-10-14 16:44 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +				let success = model->_postSaveRelatedRecords(writeConnection, related);
There should be something like `Phalcon\Mvc\Model\Worker` or `Phalcon\Mvc\Model\UnitOfWork` which will do this.

2016-10-14 16:45 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +			model->fireEvent("afterSave");
There should be something like `Phalcon\Mvc\Model\Worker` or `Phalcon\Mvc\Model\UnitOfWork` which will do this.

2016-10-14 16:45 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +			model->_cancelOperation();
There should be something like `Phalcon\Mvc\Model\Worker` or `Phalcon\Mvc\Model\UnitOfWork` which will do this.

2016-10-14 16:51 UTC, Jurigag reviewed
Worker class for model methods:
- _preSaveRelatedRecords
- _exists
- _preSave
- _doLowUpdate
- _doLowInsert
- _postSaveRelatedRecords
- _postSave
- _cancelOperation
- fireEvent
- _checkForeignKeysReverseRestrict
- _checkForeignKeysReverseCascade

So we can remove all this not needed logic in model. It should impelemnt `EvensAwareInterface` so we can attach some listener to it. Not sure about which events exactly - i guess preSave, postSave, onCancelOperation, onUpdate, onInsert ? Also as well existing model events so we can watch all model events fired for all models in one listener.

2016-10-14 17:21 UTC, Jurigag requested changes
Test cases for class implementing only ModelInterface not extending Model,  in future for any class without any interface or extending class.

2016-10-14 17:51 UTC, SidRoberts commented
What uses could a custom repository have? In my head, I imagine Repository only has [the methods listed above](https://github.com/phalcon/cphalcon/pull/12317#issuecomment-253839204) (as well as support for findFirstBy..., findBy..., countBy..., etc;).

It might be a good idea to allow the developer to overwrite the repository class via the DI:

```php
$di->set("modelRepository", "Phalcon\\Mvc\\Model\\Repository");

// OR...

$di->set("Phalcon\\Mvc\\Model\\Repository", "MyCustomRepositoryClass");
```

```zephir
let repository = <RepositoryInterface> dependencyInjector->get(
    "modelRepository",
    [modelClass, this]
);

// OR...

let repository = <RepositoryInterface> dependencyInjector->get(
    "Phalcon\\Mvc\\Model\\Repository",
    [modelClass, this]
);
```

2016-10-14 17:57 UTC, Jurigag commented
Repository also should provide query builder property(`Phalcon\Mvc\Model\Query\Builder`) and query method(`Phalcon\Mvc\Model`Criteria`). With builder we can do extensive queries. So there is example:

```php
class PersonRepository extends Repository
{
    public function findWithProfiles()
    {
        return $this->queryBuilder->from('Person')
            ->columns('*')
            ->leftJoin('Profile')
            ->getQuery()
            ->execute();
    }
}
```

2016-10-14 19:31 UTC, Jurigag commented
@SidRoberts 

Also this is really great idea. But this definitely need a hard work and implement new classes. It's not only change a few we have right now = and we have data mapper. I just add my ideas what i think should be here and how it should look. How it will be implemented and what's your idea it's up to you and someone who will merge this.

2016-10-14 19:53 UTC, SidRoberts commented
It's been a long day and after spending so much time looking at code, I can't see straight anymore. I need a good night's sleep before I can do any more serious coding.  :stuck_out_tongue_closed_eyes: I agree with your ideas about custom repositories though.

How about copying how the Models Manager deals with custom model sources and schemas (`Model::setSource()` / `Model::setSchema()`) and managing custom repositories like this:

```php
class Robots extends \Phalcon\Mvc\Model
{
	public function initialize()
	{
		$this->setRepository(
			RobotsRepository::class
		);
	}
}
```

I think I'll use this PR as a playground for ideas and redo the entire thing when the 4.0.x branch is created and everyone's opinions are taken into account.

2016-10-14 19:59 UTC, Jurigag commented
Yea This is good way BUT i'm not sure about $this->setRepository. DataMapper is all about NOT EXTENDING any class i think.

I think in result and in final form the only needed thing for our models in phalcon 4.0.0 should be a) implement interface b) use trait c) don't use anything. Im just not sure about solution. For NOW your solution is fine, but i think we should avoid ` extends \Phalcon\Mvc\Model` and in final form it should aim to not having ` extends \Phalcon\Mvc\Model` and somethign like `use Model` as a trait(as far as i know traits are just classes internally ? Correct me if im wrong. Or just only some interface for needed things to work. And repository would be just `public static function getRepository()`

2016-10-14 20:11 UTC, SidRoberts commented
I'm glad you're here - you're right and I'm thinking of solutions that require the least amount of effort to implement. :wink: 

I've never used traits but I seem to remember that it's akin to copying and pasting chunks of code, as far as the compiler is concerned.

We'll figure it out tomorrow.

2016-10-14 20:15 UTC, Jurigag commented
But im not sure, maybe there should be like totally nothing, this is up to people with more knowledge, don't if DataMapper pattern allows anything like trait or something like this. Well in doctrine there are annotations, and something is parsing them, so well - this is just some kind of "workaround" in doctrine to not having trait or something like this.

2016-10-14 20:25 UTC, SidRoberts commented
That's kind of the problem. Doctrine stores a lot of metadata in annotations and I don't think annotations will be considered fast enough. We could have metadata stored somewhere else (YAML, XML, ...) but that'd be messy. Or we could just have a few getters in Model.

2016-10-14 20:30 UTC, Jurigag commented
Or just trait and still use $this->xyz but without extends.

2016-10-14 21:19 UTC, Jurigag commented
Well it's not so easy, but maybe this is a FINALLY time to introduce traits to zephir ? @andresgutierrez @sergeyklay we are waiting already 2 years for it https://github.com/phalcon/zephir/issues/504

2016-10-14 23:12 UTC, Jurigag commented
Well i will add trait support for PHP(only atm) in zephir soon so DataMapper will work as trait in php classes.

2016-10-14 23:24 UTC, Jurigag commented on phalcon/mvc/model/repository.zep
> +	protected _modelsManager;
Oh okay, there is already `_modelsManager`, forgot what i wrote about `createBuilder` in repository then :D

2016-10-15 09:40 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +	protected function _postSave(<ModelInterface model, boolean success, boolean exists) -> boolean
Don't agree with having this in manager imho. As i wrote already we should introduce some new class.

2016-10-15 10:02 UTC, Jurigag commented
I don't like making this manager such a big class now, we definitely need new class what i already wrote imho.

2016-10-15 10:02 UTC, SidRoberts commented on phalcon/mvc/model/manager.zep
> +	protected function _postSave(<ModelInterface model, boolean success, boolean exists) -> boolean
But UnitOfWork is effectively a transaction - it only makes sense to use it if multiple models are being saved at once. I want to get all the pre/post protected methods into Manager just for now so they're all together and we can move again them later.

2016-10-15 11:11 UTC, SidRoberts commented
I've reverted the last few commits. There was a bug somewhere in there anyway. :stuck_out_tongue:

2016-10-16 18:01 UTC, Jurigag commented on phalcon/mvc/model/manager.zep
> +	public function exists(<ModelInterface> model) -> boolean
Well this can be in manager maybe, but i think the rest of `_anyMethod` from model should go to new class.

2016-10-17 09:56 UTC, allflame commented
@Jurigag on a side note: why not use doctrine as is?

2016-10-17 09:58 UTC, Jurigag commented
Because doctrine is PHP and phalcon is c and is all about performance and doctrine is slowest ORM available for php ?

2016-10-17 10:10 UTC, allflame commented
If you look into the comparison you will see a strong correlation between UoW/Datamapper (slower) - ActiveRecord (faster).
I do understand the benefits of writing Zephir code for the Phalcon ORM and maybe this is a good idea.

2016-10-17 10:11 UTC, Jurigag commented
Well this is why we have zephir and we cant create something which will be still fast enough and will get all advantages of Datamapper - but it should be a real Datamapper or be really similar to it.

2016-10-17 10:27 UTC, sergeyklay commented
abandoned project https://github.com/lynx/lynx-legacy-zephir

2016-10-22 10:19 UTC, Jurigag commented
@SidRoberts also if you will return to this it could be nice to add some event like notFound or something if result of `findFirst` don't exist in database

2016-10-22 15:31 UTC, SidRoberts commented
I'm currently working on moving the relevant unit tests to Codeception and tidying them up a bit (#12348), refactoring model classes (#12328) and doing anything else to reduce the possibility of messy merge conflicts and introducing regressions.

2016-10-28 16:53 UTC, SidRoberts commented
How about introducing this slowly over the course of version 3, keeping BC along the way and then drop BC or deprecate in version 4? Or would that be too complicated?

2016-10-28 16:54 UTC, Jurigag commented
Too complicated in my opinion. Better just create 4.0.x branch and merge it while it's be done and that's it.

2017-03-12 20:25 UTC, tempcke commented
I've been doing a lot of reading lately about data mapper vs active record and the more I read the more I like the data mapper pattern.  Though I do not like doctrine due to all the dang @annotations.  Is it your goal to replace active record with data mapper pattern or will both be available ?  Will the domain models be required to extend a base class?

2017-03-12 20:38 UTC, virgofx commented
Just a note theres no way the active record can be replaced in Phalcon as this is one of the core features of the framework. Any new ORM will need to be an additional option that doesn't impact existing active record.

2017-08-15 22:40 UTC, SidRoberts commented
I completely messed up the history and there were too many merge conflicts to deal with so I'm recreating these commits manually. The original branch is available at https://github.com/SidRoberts/cphalcon/commits/v4-model-data-mapper-original

2017-08-16 06:11 UTC, sergeyklay commented
@SidRoberts Could you please check tests

2017-08-16 17:30 UTC, merged

2017-08-16 17:30 UTC, sergeyklay commented
Thank you

2018-11-21 19:16 UTC, MufidJamaluddin commented
I think the better option is move pagination method to this repository or make new class (PagingRepository)