[WIP] Refactored Model
phalcon/cphalcon pull request #12328
Opened 2016-10-16 20:55 UTC by SidRoberts

Don't merge this just yet - there'll be a few more commits in the next few days.

2016-10-16 21:43 UTC, sergeyklay commented
@SidRoberts It is changes for `3.0.x` or for `3.1.x` ?

2016-10-16 21:50 UTC, SidRoberts commented
3.0.x - I'm just simplifying the code in the existing methods for now.

2016-10-17 22:27 UTC, sergeyklay commented
@SidRoberts It seems all ok with test. You can continue your work
Refs:
* https://github.com/Codeception/Specify/pull/35
* https://github.com/phalcon/cphalcon/pull/12332

2016-10-18 13:49 UTC, sergeyklay requested changes

2016-10-18 13:49 UTC, sergeyklay commented on phalcon/mvc/model/relation.zep
> +		return isset this->_options["foreignKey"];
```
protected _options;
```

not array

2016-10-18 13:58 UTC, sergeyklay approved these changes

2016-10-18 14:11 UTC, Jurigag commented on phalcon/mvc/model/relation.zep
> +		return isset this->_options["foreignKey"];
But won't php complain about this ?

2016-10-18 14:24 UTC, Jurigag commented on phalcon/mvc/model/relation.zep
> +		return isset this->_options["foreignKey"];
Yea i tested and it's fine in php.

2016-10-19 14:59 UTC, SidRoberts commented
@sergeyklay Assuming this passes in Travis, I think it's ready to merge.

2016-10-19 15:20 UTC, Jurigag commented
Squash please :)

2016-10-20 08:33 UTC, SidRoberts commented
I'm not on my dev machine and Serghei can rebase it when merging.

2016-10-21 08:37 UTC, merged

2016-10-21 08:38 UTC, sergeyklay commented
Thanks

2016-10-22 06:46 UTC, sergeyklay commented
@SidRoberts Now builds for 3.0.x are broken. https://travis-ci.org/phalcon/incubator/builds/169510034

Could you please take a look

2016-10-22 10:01 UTC, SidRoberts commented
Fixed in phalcon/incubator#680.

2016-10-24 12:54 UTC, Jurigag commented
```
Warning: Variable "metaData" declared but not used in Phalcon\Mvc\Model\MetaData::writeMetaDataIndex in /root/cphalcon/phalcon/mvc/model/metadata.zep on 305 [unused-variable]

          var metaData, source, schema, key;

```

@SidRoberts

2016-10-24 13:21 UTC, sergeyklay commented
Fixed