[WIP] Moved some more unit tests to Codeception
phalcon/cphalcon pull request #12357
Opened 2016-10-24 13:39 UTC by SidRoberts

2016-10-24 13:53 UTC, sergeyklay requested changes

2016-10-24 13:53 UTC, sergeyklay commented on tests/unit/Cli/RouterTest.php
> +                $di = new \Phalcon\DI\FactoryDefault\CLI();
1. Could you please use aliasing like `use Phalcon\Di\FactoryDefault\Cli?
2. Note `Di` not `DI` and `Cli` not `CLI`
3. Provide please real failed message  instead `"..."`

2016-10-24 13:53 UTC, sergeyklay commented on tests/unit/Cli/RouterTest.php
> +                expect($router->getActionName())->equals(null);
```php
expect($router->getModuleName())->null();
expect($router->getTaskName())->null();
expect($router->getActionName())->null();
```

2016-10-24 13:53 UTC, sergeyklay commented on tests/unit/Cli/RouterTest.php
> +                );
Use `examples` please: https://github.com/Codeception/Specify#examples

2016-10-24 13:53 UTC, sergeyklay commented
@SidRoberts Could you please take a look at my comments :)

2016-10-24 16:16 UTC, sergeyklay requested changes

2016-10-24 16:16 UTC, sergeyklay commented on tests/unit/Cli/ConsoleTest.php
> + * @package   Phalcon\Test\Unit
`Phalcon\Test\Unit\Cli`

2016-10-24 16:16 UTC, sergeyklay commented on tests/unit/Cli/ConsoleTest.php
> +            "...",
provide message

2016-10-24 16:16 UTC, sergeyklay commented on tests/unit/Cli/ConsoleTest.php
> +                    expect($e->getMessage())->equals("Module 'devtools' isn't registered in the console container");
Split please this test to 2 tests: the testing module and the testing namespace.

Also note if exception will not be thrown, the test will pass. This is why you have to use something like this: https://github.com/Codeception/Specify#exceptions

2016-10-24 16:16 UTC, sergeyklay commented on tests/unit/Cli/ConsoleTest.php
> +                    expect($e->getMessage())->equals('Dummy\MainTask handler class cannot be loaded');
The same

2016-10-24 16:16 UTC, sergeyklay commented on tests/unit/Cli/ConsoleTest.php
> +            "...",
the same

2016-10-24 16:16 UTC, sergeyklay commented on tests/unit/Cli/DispatcherTest.php
> + * @package   Phalcon\Test\Unit
`Phalcon\Test\Unit\Cli`

2016-10-24 16:16 UTC, sergeyklay commented on tests/unit/Cli/DispatcherTest.php
> +                $di = new \Phalcon\DI\FactoryDefault\CLI();
Use aliasing here. Di instead DI, Cli instead of CLI.

2016-10-24 17:59 UTC, sergeyklay commented
@SidRoberts Just ping me when it is ready for merging

2016-10-24 19:11 UTC, sergeyklay requested changes

2016-10-24 19:11 UTC, sergeyklay commented on tests/_data/micro/RestHandler.php
> +class RestHandler
We have `tests/_support/Helper` and `tests/_support/Module`. Why `tests/_data`?

2016-10-24 20:14 UTC, sergeyklay commented on tests/_data/micro/RestHandler.php
> +class RestHandler
ok

2016-10-24 20:14 UTC, sergeyklay approved these changes

2016-10-25 18:28 UTC, SidRoberts commented
@sergeyklay That's all for now.

2016-10-25 22:12 UTC, merged

2016-10-25 22:12 UTC, sergeyklay commented
Thanks!