Added Phalcon\Validation\Validator\Callback
phalcon/cphalcon pull request #12368
Opened 2016-10-29 14:09 UTC by Jurigag

- [ ] Make sure that the PR passes in Travis CI to make the process more efficient.
- [ ] Only use tabs for indentation.
- [ ] if needed, rebase to the proper branch before submitting your pull request.
      If it doesn't merge cleanly with master you may be asked to rebase your changes.
- [ ] Don't put submodule updates in your pull request unless they are to landed commits.
- [ ] Add tests relevant to the fixed bug or new feature. See our testing guide for
      more information.
- [ ] Phalcon 2 is written in Zephir, please do not submit commits that modify C generated
      files directly or those whose functionality/fixes are implemented in the C
      programming language
- [ ] Remove any change to ext/kernel / *.zep.c / *.zep.h files before submitting the PR

2016-10-29 17:10 UTC, Jurigag commented
Well im hardly thinking about logic of this - should message from `Callback` validator should be added if there is true returned or false ?

2016-10-29 23:38 UTC, sergeyklay requested changes

2016-10-29 23:38 UTC, sergeyklay commented on phalcon/validation/validator/callback.zep
> + | Copyright (c) 2011-2016 Phalcon Team (https://phalconphp.com)       |
Could you please fix indents?

2016-10-29 23:38 UTC, sergeyklay commented on phalcon/validation/validator/callback.zep
> + *                 if(!empty($data->getUser()) && !empty($data->getAdmin())) {
`if(` => `if (`

2016-10-29 23:38 UTC, sergeyklay commented on phalcon/validation/validator/callback.zep
> + *                     return false
`false;`

2016-10-29 23:38 UTC, sergeyklay commented on phalcon/validation/validator/callback.zep
> + *                 if(!empty($data->getProduct())) {
`if (`

2016-10-29 23:38 UTC, sergeyklay commented on phalcon/validation/validator/callback.zep
> +			else {
else not needed

2016-10-29 23:38 UTC, sergeyklay commented on phalcon/validation/validator/exception.zep
> + | Copyright (c) 2011-2016 Phalcon Team (https://phalconphp.com)       |
indents

2016-10-29 23:38 UTC, sergeyklay commented on phalcon/validation/validator/exception.zep
> + *
extra line

2016-11-04 14:21 UTC, Jurigag commented
@sergeyklay ready to merge ? or anything more to do here ?

2016-11-04 14:38 UTC, merged

2016-11-04 14:38 UTC, sergeyklay commented
Thanks

2016-11-04 14:40 UTC, sergeyklay commented
@Jurigag Could you please submit a PR to the docs repo?

2016-11-04 14:43 UTC, Jurigag commented on CHANGELOG.md
> +# [3.1.0](https://github.com/phalcon/cphalcon/releases/tag/v3.1.0) (2016-XX-XX)``
Oh i added not needed 
```
``
```
here @sergeyklay

2016-11-04 14:44 UTC, sergeyklay commented on CHANGELOG.md
> +# [3.1.0](https://github.com/phalcon/cphalcon/releases/tag/v3.1.0) (2016-XX-XX)``
WIll be fixed in nex PR