Tag no longer uses static methods.
phalcon/cphalcon pull request #12379
Opened 2016-10-30 19:37 UTC by SidRoberts

2016-11-10 12:54 UTC, yankos commented
Hm... Is it good?
Tag as class with static method is not ideal. But this PR do not bring something new.
I think much better if Tag will be as service.

2016-11-10 12:58 UTC, Jurigag commented
Yea, don't like creating new tag object in each method.

2016-11-10 13:42 UTC, sergeyklay commented
@Jurigag Just inject Tag to the Di and use `$this->tag`, `$di->get('tag')`. And yes, I agree with @yankos about service

2016-11-10 13:47 UTC, Jurigag commented
Yea i know, but it should happen then in this PR everywhere i think. As well this would require Tag in factorydefault perhaps.

2016-11-10 14:20 UTC, yankos commented
@Jurigag of course Tag must be in factorydefault.

So, maybe it's time to refactor Tag as service for 4 version of Phalcon? 
I can to do this.

2016-11-11 21:04 UTC, SidRoberts commented
Static methods are glorified functions with namespaces. Using them in this way means we can't override them with a custom tag class and they're hard dependencies. It defeats the whole point of object-oriented programming. For all intents and purposes, they're effectively evil. :p

This PR is still a work in progress and I plan to get the 'tag' service from the DI instead of just creating a new instance every time. Unfortunately the PR doesn't pass in its current form so I'm focusing on that first.

2017-09-02 06:40 UTC, sergeyklay requested changes

2017-09-02 06:40 UTC, sergeyklay commented on phalcon/assets/manager.zep
> +		let tag = new Tag();
@SidRoberts Can we seek it in the Di first?

2017-09-02 06:40 UTC, sergeyklay commented on phalcon/assets/manager.zep
> +		let tag = new Tag();
The same

2017-09-02 06:40 UTC, sergeyklay commented on phalcon/assets/manager.zep
> +		let tag = new Tag();
and here

2018-12-11 21:46 UTC, niden commented
Addressed in https://github.com/phalcon/cphalcon/pull/13656

2018-12-11 21:46 UTC, closed without merging