Fix modelsCache snapshot
phalcon/cphalcon pull request #12458
Opened 2016-12-07 20:48 UTC by Jurigag

Hello!

* Type: bug fix
* Link to issue: no issue

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: when was fixing saving manual saving models to cache i didn't checked modelsCache. Not it should work fine.

Thanks

2016-12-07 21:20 UTC, sergeyklay requested changes

2016-12-07 21:20 UTC, sergeyklay commented on tests/unit/Mvc/ModelTest.php
> +    public function testModelsCacheSnapshot(UnitTester $I)
```php
UnitTester $I
```

needed only for `Cest` tests

2016-12-07 21:20 UTC, sergeyklay commented on tests/unit/Mvc/ModelTest.php
> +        $I->haveServiceInDi(
could you please use `addServiceToContainer` insted of `haveServiceInDi` to avoid future refactoring

2016-12-08 09:00 UTC, Jurigag commented
@sergeyklay it's ready to merge

2016-12-08 09:10 UTC, sergeyklay requested changes

2016-12-08 09:10 UTC, sergeyklay commented on tests/unit/Mvc/ModelCest.php
> +                return new Apc(new Data(['lifetime' => 20]));
@Jurigag Could you please use another, more standard cache driver here to avoid checks for APC?

2016-12-08 09:10 UTC, sergeyklay commented on tests/unit/Mvc/ModelCest.php
> +namespace Phalcon\Test\unit\Mvc;
`unit` => `Unit`

2016-12-08 09:12 UTC, Jurigag commented on tests/unit/Mvc/ModelCest.php
> +                return new Apc(new Data(['lifetime' => 20]));
Okay, will do it later.

2016-12-08 19:34 UTC, virgofx commented
Pulled @Jurigag 's PR and tested with File cache which works restoring cache for both `Simple` and `Complex`

👍  

Can we get this merged and baked into 3.0.3 ASAP -- Production builds now have caching disabled!

2016-12-08 20:00 UTC, sergeyklay commented
@Jurigag ?

2016-12-08 20:31 UTC, Jurigag commented
Updating tests.

2016-12-08 20:42 UTC, virgofx commented
I'll re-check on my branch in a little bit.

2016-12-08 22:14 UTC, sergeyklay commented on tests/unit/Mvc/Model/Query/BuilderCest.php
> +                return new File(
If extension apc is not loaded this test will be skiped

2016-12-09 13:24 UTC, sergeyklay approved these changes

2016-12-09 13:24 UTC, merged

2016-12-09 13:24 UTC, sergeyklay commented
Thanks