[3.1.x] feat(Micro): Response handler
phalcon/cphalcon pull request #12452
Opened 2016-12-03 11:39 UTC by Doehl

* Type: new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

## Small description of change:

**What:**
Adds the possibility to create a response handler, that will handle the
response instead of the default hard coded micro handler.

**Why:**
Before the reponse format had to be coded into every route.
Now is it possible to create a custom rosponse handler, that will format
the data in custom created function.

**Changes to phalcon/mvc/micro.zep**
* Added **protected** class variable **_responseHandler**
_The custom response handler_

* Added **public** function **response** 
_Appends a response handler_

* Change to **public** function  **handle** 
_Check if a response handler has been appended._
_If **yes**, run the response handler._
_If **no**, run the same code as before this PR._

## Unit test
Adds a response handler, and check if it has been called.

## How to use
```php
$app->response(function () use ($app) {

    // Gets the client response, that has been returned from executed route
    $return = $app->getReturnedValue();

    // Put controller return array item data
    $return = array('data' => $return);

    // Set reponse Content-Type to json
    header('Content-Type: application/json');

    // Print json response string
    echo json_encode($return);
});
```

2016-12-03 12:03 UTC, Jurigag commented
Squash commits please.

2016-12-03 13:11 UTC, Doehl commented
The commits has been squashed.

2016-12-11 19:27 UTC, sergeyklay commented
@Doehl Could you please rebase

2016-12-12 13:41 UTC, Doehl commented
Rebase done

2016-12-12 16:25 UTC, sergeyklay requested changes

2016-12-12 16:25 UTC, sergeyklay commented on phalcon/mvc/micro.zep
> +	public function response(handler) -> <Micro>
I would like that this method was named `setResponseHandler`

2016-12-12 16:25 UTC, sergeyklay commented on phalcon/mvc/micro.zep
> +	 * @return \Phalcon\Mvc\Micro
the `@return` not needed here

2016-12-12 16:29 UTC, sergeyklay commented on phalcon/mvc/micro.zep
> +			call_user_func(this->_responseHandler);
How about `let returnedValue = call_user_func(this->_responseHandler);`

2016-12-12 16:38 UTC, Doehl commented on phalcon/mvc/micro.zep
> +	public function response(handler) -> <Micro>
I did try to keep it the same as "after", "before" and "finish" functions.
But if that is how we should name function, I will of course change it.

2016-12-12 16:39 UTC, Doehl commented on phalcon/mvc/micro.zep
> +	 * @return \Phalcon\Mvc\Micro
Remove it I will.

2016-12-12 16:50 UTC, Doehl commented
All the changes has been made.

2016-12-12 21:38 UTC, sergeyklay approved these changes

2016-12-12 21:39 UTC, sergeyklay commented
@virgofx Could you please take a look

2017-04-26 09:33 UTC, sergeyklay commented
Cc: @phalcon/core-team

2018-10-17 19:21 UTC, niden commented
@Doehl Would you be so kind as to rebase this to the `3.4.x` branch and also issue one more for the `4.0.x` branch? 

Thanks for the work!

2018-11-17 21:32 UTC, Doehl commented
Hi niden,

Sorry for the late response.
I do not use the phalcon framework at the moment, and does no longer have access to the setup on where I had the phalcon environment running. Because of change on job.

I would love to help, but do no longer have access to an environment where I can easily help with this PR any longer.

2018-11-23 13:43 UTC, niden commented
@Doehl Not a problem. I can just "move" your work to a different branch so that you can get credit for this work :)

Thank you again and whenever you have the time we would welcome your contributions.

2018-12-08 15:22 UTC, closed without merging

2018-12-28 02:49 UTC, gspgsp commented
2018/12/28 10:37:48 [error] 14931#0: *18 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught BadMethodCallException: Wrong number of parameters in /www/wechat-api/app/bootstrap/bootstrap.php:13

my bootstrap.php code is:
<?php
use Phalcon\Mvc\Micro;
use Quickapi\App\Service\Helper;

$micro = new Micro($di);
Helper::mountRoutes($micro, $routes); #$routes is in the same document
$micro->handle(); #this is line 13 , i don't konw why ,befor in php5.6  phalcon version 3, there is no problem ,today  i use php7.2 and the phalcon version is also update to 4.0

2018-12-28 03:02 UTC, niden commented
@gspgsp Please have a look at this blog post for a list of things that changed:

https://blog.phalconphp.com/post/upgrading-to-v4-alpha-1

Something you are using in your bootstrap file has changed and now you need to adjust your parameters.