Type time
phalcon/cphalcon pull request #12471
Opened 2016-12-13 07:56 UTC by ruudboon

Rebased upon request https://github.com/phalcon/cphalcon/pull/12293 
@sergeyklay Looked at the other added Column types but didn't see any changed test. What test do you want me to change?

2016-12-13 08:40 UTC, sergeyklay commented
I would like you to create a small test ([see example here](https://github.com/phalcon/cphalcon/blob/3.0.x/unit-tests/DbDialectTest.php)) using this namespace https://github.com/phalcon/cphalcon/tree/master/tests/unit/Db/Column

2016-12-13 16:12 UTC, sergeyklay requested changes

2016-12-13 16:12 UTC, sergeyklay commented on phalcon/db/adapter/pdo/mysql.zep
> +                                let definition["type"] = Column::TYPE_TIME;
Could you please fix indents

2016-12-13 16:12 UTC, sergeyklay commented on phalcon/db/adapter/pdo/postgresql.zep
> +                                 */
and here

2016-12-13 16:14 UTC, ruudboon commented on phalcon/db/adapter/pdo/postgresql.zep
> +                                 */
Sorry, missed that. Will fix it. Still working on those unit test btw. Try to push them today.

2016-12-13 18:04 UTC, sergeyklay requested changes

2016-12-13 18:04 UTC, sergeyklay commented on phalcon/db/dialect/mysql.zep
> +                                break;
there still issue with indents

2016-12-13 18:04 UTC, sergeyklay commented on phalcon/db/dialect/postgresql.zep
> +                                break;
and here

2016-12-13 18:06 UTC, sergeyklay commented
Could you provide a solution for the SQLite. I mean converting TIME to date type, etc

2016-12-14 14:17 UTC, ruudboon commented
I think everything is in. If there's more needed please let me know.

2016-12-14 18:12 UTC, sergeyklay requested changes

2016-12-14 18:12 UTC, sergeyklay commented on phalcon/db/dialect/sqlite.zep
> +					let columnSql .= "TIME";
Are you sure about this? https://www.sqlite.org/datatype3.html#date_and_time_datatype

That's why I asked you to provide a workaround. That is why we are not in a hurry to take all possible data types.

2016-12-14 18:25 UTC, sergeyklay requested changes

2016-12-14 18:25 UTC, sergeyklay commented on tests/unit/Db/Column/MysqlTest.php
> +        $this->assertEquals($dialect->getColumnDefinition($column), 'TIME');
I'd like to see here a test for the table that has this data type. Please understand me correctly. We can't release framework with black box. 

For example:

```sql
CREATE TABLE `entries` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `start` TIME NOT NULL DEFAULT CURRENT_TIME,
  `end` TIME DEFAULT '23:59',
  `add` TIME NULL,
  `amount` INT NOT NULL,
  `price` INT NOT NULL
);
```

Could you please convert this into objects and back?

2016-12-14 18:25 UTC, sergeyklay commented on tests/unit/Db/Column/PostgresqlTest.php
> +        $this->assertEquals($dialect->getColumnDefinition($column), 'TIME');
See my comment for MysqlTest

2016-12-14 18:25 UTC, sergeyklay commented on tests/unit/Db/Column/SqliteTest.php
> +        $this->assertEquals($dialect->getColumnDefinition($column), 'TIME');
See my comment for MysqlTest

2016-12-14 19:46 UTC, ruudboon commented on tests/unit/Db/Column/MysqlTest.php
> +        $this->assertEquals($dialect->getColumnDefinition($column), 'TIME');
Hmm I get it. Makes sense! Shouldn't we have them for datetime etc also? 
Thnx 4 all the feedback. Appreciate the effort, kinda new to this.

2017-01-12 15:22 UTC, Jurigag commented on tests/unit/Db/Column/MysqlTest.php
> +        $this->assertEquals($dialect->getColumnDefinition($column), 'TIME');
There is already `TYPE_DATETIME` and `TYPE_DATE`

2017-02-22 19:29 UTC, david-duncan commented
This hasn't seen activity in two months - can we get review fixes pushed and for this PR to get squashed?

2017-09-19 19:58 UTC, ruudboon commented
Currently looking into this (first need to setup a new dev env). 
Looks like the unit tests are changed a bit. Some pointer would be helpful.

2017-09-19 20:13 UTC, Jurigag commented
You need to rebase it.

2017-11-08 08:36 UTC, ruudboon commented
Just wanna give heads up that I did some work on this issue (https://github.com/ruudboon/cphalcon/commit/ce2408dca9fed7803b08ff33682c98d79e50c8b3). Trying to finish unit tests and get Travis to work on my branch before submitting a new pull.

2018-10-31 14:23 UTC, niden commented
Addressed in https://github.com/phalcon/cphalcon/pull/13562

2018-10-31 14:23 UTC, closed without merging