fix compilation when imagemagick is v7
phalcon/cphalcon pull request #12493
Opened 2016-12-22 08:17 UTC by Izopi4a

Hello!

when image magick version is 7 compilation fails

2016-12-22 08:39 UTC, sergeyklay requested changes

2016-12-22 08:39 UTC, sergeyklay commented on phalcon/image/adapter/imagick.zep
> +		if version_compare(imagickVersion[1], '7') < 0 {
`'7'` -> "7"

2016-12-22 08:41 UTC, sergeyklay commented
Also could you please update `CHANGELOG.md`

2016-12-22 09:17 UTC, elibyy commented
why not use method_exists?

2016-12-22 09:20 UTC, Izopi4a commented
well i might have to cuz preg_match might be broken in php5 ( for zephir ) , but if I use method exists , if they change that shit again in imagick 8 the code will look funny xD

2016-12-22 09:27 UTC, sergeyklay commented
@Izopi4a Well, as you can see tests fails

2016-12-22 09:40 UTC, Jurigag commented on phalcon/image/adapter/imagick.zep
> +		preg_match("/ImageMagick ([0-9]+\.[0-9]+\.[0-9]+)/", imagickVersion["versionString"], tmp);
for what is this preg_match ? Just compare below against 7.0.0

2016-12-22 12:10 UTC, Izopi4a commented
i will fix windows build these days because i need to dig into that

2016-12-22 12:22 UTC, Jurigag commented
`Class '\Imagick' does not implement static method: 'getVersion'`, hmmm imagick not loaded on windows or what ?

2016-12-24 00:06 UTC, sergeyklay commented
Fixed in the `3.0.x` branch.

2016-12-24 00:06 UTC, closed without merging