Fixed model field default value
phalcon/cphalcon pull request #12507
Opened 2016-12-26 09:02 UTC by zGaron

as comment.
if the field is  " not null default '' " in database.
model.zep:2091 while return null.

Thanks

2016-12-26 09:15 UTC, sergeyklay commented
@zGaron Could you please provide a small script to reproduce the issue?

2016-12-26 09:50 UTC, zGaron commented
@sergeyklay 

just in update

```php
        $db = Di::getDefault()->get('db');
        
        $table_name = "bugfix_12507";
        
        
        $ddl = "CREATE TABLE {$table_name}(id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, test_field VARCHAR(12) DEFAULT '' NOT NULL);";
        $ret = $db->execute($ddl);
        if (!$ret) {
            var_dump('create test table failed!');
        }
        
        
        $modelClass = "Bugfix12507";
        $modelCde   = "Class {$modelClass} extends Phalcon\\Mvc\\Model {" . PHP_EOL .
            "public \$id;" . PHP_EOL .
            "public \$test_field;" . PHP_EOL .
            "public function getSource(){ return '{$table_name}';}" . PHP_EOL .
            "}" . PHP_EOL;
        eval($modelCde);
    
        /**
         * @var Model $model
         */
        $model = new $modelClass();
        $model->test_field = '';
        $ret = $model->create();
        if(!$ret) {
            echo "on create!", "<br/>";
            $message = $model->getMessages();
            /**
             * @var $msg Model\Message
             */
            foreach ($message as $msg) {
                echo $msg->getMessage(), '<br/>';
            }
        }
    
        $model->test_field = time();
        $model->save();
    
        $model = $modelClass::findFirst(1);
        $model->test_field = '';
        $ret = $model->save();
        
        if(!$ret) {
            echo "on update!", "<br/>";
            $message = $model->getMessages();
            /**
             * @var $msg Model\Message
             */
            foreach ($message as $msg) {
                echo $msg->getMessage(), '<br/>';
            }
        }
        
        $db->execute('DROP TABLE '.$table_name);
```

2016-12-28 02:55 UTC, zGaron commented
hi @sergeyklay 
I  have added a unit test for this PR, please see if this is the one you want.

2016-12-28 06:50 UTC, sergeyklay commented
@zGaron Could you please submit this PR to the 3.0.x branch. I'll merge 3.0.x with 3.1.x later. Also update please CHANGELOG.md

2016-12-28 07:27 UTC, zGaron commented
@sergeyklay  ok

2016-12-28 07:35 UTC, sergeyklay requested changes

2016-12-28 07:35 UTC, sergeyklay commented on CHANGELOG.md
> +- Fixed default value of the model is not correct properly when updating. [#12507](https://github.com/phalcon/cphalcon/issues/12507)
The 3.0.3 already released. Use 3.0.4 please

2016-12-28 07:37 UTC, zGaron commented on CHANGELOG.md
> +- Fixed default value of the model is not correct properly when updating. [#12507](https://github.com/phalcon/cphalcon/issues/12507)
XD
got it

2016-12-28 07:42 UTC, zGaron commented
@sergeyklay 
Can I use [ci skip] when I just modify the CHANGELOG.md ?

2016-12-28 09:08 UTC, sergeyklay approved these changes

2016-12-28 09:08 UTC, merged

2016-12-28 09:08 UTC, sergeyklay commented
Thanks