Added DI services loading from php/yaml file for readability
phalcon/cphalcon pull request #12517
Opened 2016-12-29 13:34 UTC by gguridi

Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Dependency injection is the container of any instance declaration in the system. Theoretically any instance should be obtained through dependency injection, which means that in a normal website/application we can end up with lots of classes set in the di as a services. The current system to add services into the dependency injection object require the di itself, setting them one by one.

This pull request is to enable the load of the services from yaml or php files. This is not a big feature and won't solve any real problem, but I just though it would make things more readable as we can have one file with the declaration of the dependencies without having to call di methods, parameters, etc.

This just improves readability, nothing else.

Thanks

2016-12-29 13:39 UTC, Jurigag commented
Update changelog.md please too

2016-12-29 13:39 UTC, Jurigag requested changes
Update changelog.md please too

2016-12-30 16:50 UTC, gguridi commented
Added changes into the changelog.

2017-01-03 16:58 UTC, Fenikkusu requested changes

2017-01-03 16:58 UTC, Fenikkusu commented on phalcon/di.zep
> +			let shared = isset service["shared"] ? service["shared"] : true;
You should probably change the default to false. The default for set's $shared variable is false. You are forcing all items to be shared items by default when loaded from the config. This is counter to current setups.

2017-01-09 22:13 UTC, sergeyklay approved these changes

2017-01-12 11:43 UTC, Jurigag approved these changes

2017-02-14 13:41 UTC, Jurigag commented
Can you please rebase so it could be merged?

2017-04-11 21:50 UTC, sergeyklay commented
Implemented in the `3.2.x` branch. Thank you for contributing.

2017-04-11 21:50 UTC, closed without merging