Added retainer for current session token in order to not break checkToken functionality if getToken is called before.
phalcon/cphalcon pull request #12518
Opened 2016-12-29 16:02 UTC by gguridi

…ate fields after regenerating the token. Added string casting to userToken.

Hello!

* Type: bug fix | new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/12392

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Security::checkToken functionality doesn't use the regenerated session but uses the one that was set at the beginning if it existed. This will prevent that if we call getToken and the session token is regenerated, the checkToken method will fail because the session token has changed.

I've also cast to string the userToken coming from the request::getPost method as it could be null and I was receiving an E_WARNING when passing it to hash_equals.

Thanks

2016-12-29 16:11 UTC, Jurigag requested changes
Update `CHANGELOG.md` please too

2017-01-03 06:10 UTC, sergeyklay requested changes
@gguridi We use the `3.0.x` branch for bug fixes that do not break backward compatibility. I changed the base branch to `3.0.x` from `3.1.x`. But now your PR  has conflicts that must be resolved. So could you please rebase the PR onto `3.0.x` branch?

2017-01-09 22:10 UTC, sergeyklay commented
@gguridi Could you please rebase again? This PR has conflicts (CHANGELOG.md) after merging https://github.com/phalcon/cphalcon/pull/12515

2018-12-09 15:42 UTC, niden commented
This has been implemented with PR https://github.com/phalcon/cphalcon/pull/13642

2018-12-09 15:42 UTC, closed without merging