IP generic validator.
phalcon/cphalcon pull request #12513
Opened 2016-12-28 15:37 UTC by gguridi

Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
- This is a generic ip validator for general purposes. The MVC models have one but it couldn't be used for generic forms so I've created if with the unit tests associated.

Thanks

2016-12-28 21:48 UTC, Jurigag commented
Reopen PR cuz failing tests seems unrelated.

2016-12-29 13:43 UTC, Jurigag commented on CHANGELOG.md
> +- Added ip generic validator so we can add ip textfields into forms, etc.
I would like more:
> Added `Phalcon\Validation\Validator\Ip` ... IP ...

2016-12-30 16:43 UTC, gguridi commented
Added the changes requested in the changelog file.

2016-12-30 16:55 UTC, Jurigag commented on CHANGELOG.md
> +- Added `Phalcon\Validation\Validator\Ip`, class used to validate ip address fields. It allows to validate a field selecting IPv4 or IPv4, allowing private or reserved ranges and empty values if nece
IPv4 OR IPv**6**

2016-12-30 17:10 UTC, gguridi commented on CHANGELOG.md
> +- Added `Phalcon\Validation\Validator\Ip`, class used to validate ip address fields. It allows to validate a field selecting IPv4 or IPv4, allowing private or reserved ranges and empty values if nece
Damn! :) Fixed.

2017-01-03 05:59 UTC, sergeyklay requested changes
We use the 3.0.x branch is only for bugfixes. Could you please submit this PR to the 3.1.x branch?

2017-01-03 05:59 UTC, sergeyklay commented on phalcon/validation/validator/ip.zep
> + | Copyright (c) 2011-2016 Phalcon Team (https://phalconphp.com)       |
1. `2011-2017`
2. Could you please fix the indent issue

2017-01-03 05:59 UTC, sergeyklay commented on phalcon/validation/validator/ip.zep
> + | Authors: Gorka Guridi <gorka.guridi@gmail.com>                         |                    |
Extra `                    |`

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> + * @copyright (c) 2011-2016 Phalcon Team
`2011-2017`

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            $this->assertEmpty($messages, 'Ip address should be valid');
```php
expect($validation->validate(['ip' => '127.0.0.1']))->isEmpty();
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            $this->assertEmpty($messages, 'Ip address should be valid');
```php
expect($validation->validate(['ip' => '192.168.10.20']))->isEmpty();
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            $this->assertEmpty($messages, 'Empty ip address should be valid.');
```php
expect($validation->validate(['ip' => '']))->isEmpty();
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            $this->assertNotEmpty($messages, 'Ip version 6 should not be valid');
```php
expect($validation->validate(['ip' => '2001:cdba:0000:0000:0000:0000:3257:9652']))->notEmpty();
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            $this->assertNotEmpty($messages, 'Ip address should not be valid');
```php
expect($validation->validate(['ip' => '127.0.0.1']))->notEmpty();
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            $this->assertNotEmpty($messages, 'Ip address should not be valid');
```php
expect($validation->validate(['ip' => '192.168.10.20']))->notEmpty();
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            $this->assertNotEmpty($messages, 'Empty ip address should not be valid.');
```php
expect($validation->validate(['ip' => '']))->notEmpty();
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            expect($messages->count())->equals(1);
```php
expect($messages)->count(1);
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            expect($messages->count())->equals(1);
```php
expect($messages)->count(1);
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            expect($messages->count())->equals(0);
```php
expect($messages)->count(0);
```

2017-01-03 05:59 UTC, sergeyklay commented on tests/unit/Validation/Validator/IpTest.php
> +            expect($messages->count())->equals(1);
```php
expect($messages)->count(1);
```

2017-01-03 09:30 UTC, Jurigag commented
It's already onto 3.1.x @sergeyklay

2017-01-03 11:26 UTC, sergeyklay commented
Oh, yes. Well, we need tune up the IpTest

2017-03-08 19:59 UTC, Jurigag commented
@gguridi will you go back to this PR?

2017-03-20 11:40 UTC, Jurigag commented
If this will be accepted for 3.1.x by @sergeyklay update also https://github.com/phalcon/cphalcon/blob/3.1.x/phalcon/mvc/model/validator/ip.zep to add here `@see`

2017-03-22 17:45 UTC, gguridi commented
The CHANGELOG.md is again in conflict.

But it has a top line 3.2.0 (2017-XX-XX)... shouldn't the branch 3.1.x know nothing about 3.2.x branch? It's like the past knowing what's gonna happen in the future...

2017-03-22 18:07 UTC, Jurigag commented
I agree

2017-03-23 11:07 UTC, Jurigag commented
Well i guess right now you should change base to 3.2.x so we will add it in 3.2.0

2017-03-23 15:39 UTC, gguridi commented
Changed base to 3.2.x

2017-03-23 15:56 UTC, Jurigag requested changes
Update also https://github.com/phalcon/cphalcon/blob/3.1.x/phalcon/mvc/model/validator/ip.zep to add here `@see`

2017-04-29 08:37 UTC, Jurigag commented
@gguridi can you rebase and squash commits?

2018-11-01 00:41 UTC, niden commented
@gguridi Thank you for all this work. Apologies for not getting to this earlier.

Would you be so kind as to rebase this with the current `3.4.x` branch and also issue a PR with the same work in for the `4.x` branch?

Thank you again

2018-11-01 15:58 UTC, gguridi commented
@niden I will try to do it as soon as possible.

2018-11-01 18:29 UTC, niden commented
@gguridi Thank you Sir!

2018-11-03 12:41 UTC, gguridi commented
@niden Updated this PR and created [PR 13574](https://github.com/phalcon/cphalcon/pull/13574) for the 4.0.x branch. Seems that branch 3.4.x tests are broken though.

2018-11-29 03:24 UTC, closed without merging