Added smallint support in Phalcon\Db
phalcon/cphalcon pull request #12523
Opened 2017-01-02 19:08 UTC by Studentsov

This patch adds the capability to use the data type smallint, which is part of the SQL standard and is well supported by major DBMS. This data type uses 2 bytes instead of 4 bytes for type int, which will save memory if you don't need large numeric values.

2017-01-03 05:44 UTC, sergeyklay requested changes
@Studentsov Could you please cover new feature by unit tests?

2017-01-03 05:44 UTC, sergeyklay commented on phalcon/db/column.zep
> +	const TYPE_SMALLINTEGER = 18;
How about just `TYPE_SMALLINT`?

2017-01-03 09:07 UTC, Studentsov commented on phalcon/db/column.zep
> +	const TYPE_SMALLINTEGER = 18;
We already have a type TYPE_BIGINTEGER. It would be very strange (though quite in the spirit of PHP 😆) to use the name TYPE_SMALLINT.

2017-01-03 11:27 UTC, sergeyklay commented on phalcon/db/column.zep
> +	const TYPE_SMALLINTEGER = 18;
agree

2017-01-03 11:27 UTC, sergeyklay approved these changes

2017-03-14 11:52 UTC, Jurigag commented
Can you add here tinyint support too?

2017-03-14 11:59 UTC, Studentsov commented
As far is I known, the one-byte integer type isn't provided by the SQL
standard. For example, it isn't in PostgreSQL.

2017-03-14 12:06 UTC, Jurigag commented
Oh okay, so it could be at least added to mysql. Not sure about Column class.

2018-10-16 21:07 UTC, niden commented
@Studentsov Could you be so kind as to rebase this for the `3.4.x` branch so that we can merge this?

Apologies for letting this linger for this long

2018-10-31 14:23 UTC, niden commented
Addressed in https://github.com/phalcon/cphalcon/pull/13562

2018-10-31 14:23 UTC, closed without merging