Added ability to get original values from model binder
phalcon/cphalcon pull request #12559
Opened 2017-01-19 14:05 UTC by Jurigag

Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: with introducing `Phalcon\Mvc\Model\Binder` which will change values in dispatcher loop for parameters sometimes you would like to have ability to get original values for example caching related stuff. This PR is adding way to return original values before changing them to models.

Thanks

2017-01-19 19:45 UTC, sergeyklay commented on phalcon/dispatcher.zep
> +		return this->_modelBinder;
 Could you please add this to the changelog

2017-01-19 19:46 UTC, sergeyklay requested changes

2017-01-19 19:46 UTC, sergeyklay commented on phalcon/mvc/micro.zep
> +		return this->_modelBinder;
 Could you please add this to the changelog

2017-01-19 19:46 UTC, sergeyklay commented on phalcon/dispatcher.zep
> +	}
 Could you please add this to the changelog

2017-01-19 19:46 UTC, sergeyklay commented on phalcon/mvc/micro.zep
> +		return this->_modelBinder;
Or null?

2017-01-19 19:46 UTC, sergeyklay commented on phalcon/dispatcher.zep
> +	}
Or null?

2017-01-19 20:07 UTC, Jurigag commented on phalcon/dispatcher.zep
> +	}
There is many methods in whole framework like getter which have only class returned without `|null`.

2017-01-24 13:54 UTC, Jurigag commented
@sergeyklay anything more?

2017-01-24 16:17 UTC, sergeyklay commented
Could you please rebase?

2017-01-25 13:20 UTC, Jurigag commented
@sergeyklay rebased

2017-01-25 14:03 UTC, sergeyklay approved these changes

2017-01-25 19:00 UTC, merged

2017-01-25 19:00 UTC, sergeyklay commented
Thanks