Phalcon\Session\Bag: add of initialization for remove()
phalcon/cphalcon pull request #12647
Opened 2017-02-22 10:41 UTC by morafabio

* Type: bug fix
* Issue: when `Phalcon\Session\Bag` is restored by the session handler, the `_data` property results not initialized and `remove()` won't work properly.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.  

Small description of change:  Initialization steps in `remove()` have been added.

Steps to reproduce:

       <?php
       
        // debug with reflection
        $reflectionClass = new \ReflectionClass(get_class($this->bag));
        $_data = $reflectionClass->getProperty('_data');
        $_data->setAccessible(true);
        $_initialized = $reflectionClass->getProperty('_initialized');
        $_initialized->setAccessible(true);

        // create a Bag with one value
        $bag = new \Phalcon\Session\Bag('fruit');
        $bag->set('apples', 10);
        var_dump($bag->get('apples')); // int(10)
        var_dump($_data->getValue($bag)); // array(1) { ["apples"]=> int(10) }
        var_dump($_initialized->getValue($bag)); // bool(true)

        // save and cleanup
        $serializedBag = serialize($bag);
        unset($bag);

        // emulate restore in the same way it would be done
        // any PHP session handler, e.g.: `session.save_handler => redis => redis`
        $bag = unserialize($serializedBag);
        $_data->setValue($bag, NULL);
        $_initialized->setValue($bag, false);

        // remove attempt fails because `_data` is NULL
        var_dump($bag->remove('apples')); // bool(false) // EXPECTED: bool(true)
        var_dump($bag->get('apples')); // int(10) // EXPECTED: NULL

        // get performs _initialize under the hood, so now it works
        var_dump($bag->remove('apples')); // bool(true)
        var_dump($bag->get('apples')); // NULL

this calls initialize also on `Bag::remove`.

Run tests: `vagrant@phalcon:~/cphalcon$ vendor/bin/codecept run tests/unit/Session/BagTest`

Thanks

2017-02-22 10:52 UTC, sergeyklay requested changes

2017-02-22 10:52 UTC, sergeyklay commented on CHANGELOG.md
> +
Could you please add this to bottom of the `[3.1.0]` section?

2017-02-22 11:05 UTC, morafabio commented
@sergeyklay `ManagerTest` looks failing but I have no idea on how this is related to my change. Any hint :)?

2017-02-22 11:33 UTC, morafabio commented
Hum... Lookes the the build of `3.1.0` was already failing: https://travis-ci.org/phalcon/cphalcon/jobs/203022574

2017-02-22 12:24 UTC, morafabio commented on CHANGELOG.md
> +
Done

2017-02-22 12:28 UTC, sergeyklay commented
Will be fixed after https://github.com/phalcon/cphalcon/pull/12644

2017-02-22 12:30 UTC, morafabio commented
Ok, so do you need me to fix something other?

2017-02-22 12:41 UTC, sergeyklay commented
I'll take a look later. Thank you for contributing.

2017-02-22 12:41 UTC, morafabio commented
👍

2017-02-25 21:17 UTC, sergeyklay commented
Thank you. Merged to the 3.1.x

2017-02-25 21:17 UTC, closed without merging