Need to check that response has not been already sent in phalcon/mvc/micro.zep
phalcon/cphalcon pull request #12668
Opened 2017-03-01 07:51 UTC by Fabsolute

Hello!

* Type: bug fix

**In raising this pull request, I confirm the following :**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

It is not possible to return a string value from a mapped function for an HTTP Method, and then catch that returned value by using Micro::getReturnedValue() method inside handler on Micro::after($handler), its overriding my response.

Thanks

2017-03-01 08:18 UTC, Jurigag commented
This is bug fix. It should be made to 3.0.x, also update changelog.

2017-03-03 08:28 UTC, Fabsolute commented
Changelog updated.

2017-03-08 09:53 UTC, Jurigag commented
I mean unit test.

2017-03-08 11:48 UTC, sergeyklay requested changes
@Fabsolute In general I like this PR. Could you please provide a small test which covers these changes?

2017-03-10 09:43 UTC, sergeyklay requested changes
@Fabsolute 

```
FILE: /home/travis/build/phalcon/cphalcon/tests/unit/Mvc/MicroTest.php
----------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 4 LINES
----------------------------------------------------------------------
 451 | ERROR | [x] Expected 1 space after USE keyword; found 0
     |       |     (Squiz.Functions.MultiLineFunctionDeclaration.SpaceAfterUse)
 451 | ERROR | [x] Expected 1 space before opening brace; found 0
     |       |     (Squiz.Functions.MultiLineFunctionDeclaration.SpaceBeforeBrace)
 458 | ERROR | [x] Expected 1 space before opening brace; found 0
     |       |     (Squiz.Functions.MultiLineFunctionDeclaration.SpaceBeforeBrace)
 459 | ERROR | [x] Line indented incorrectly; expected at least 24
     |       |     spaces, found 23
     |       |     (Generic.WhiteSpace.ScopeIndent.Incorrect)
 467 | ERROR | [x] The closing brace for the class must go on the next
     |       |     line after the body
     |       |     (PSR2.Classes.ClassDeclaration.CloseBraceAfterBody)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 5 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

2017-03-10 14:51 UTC, sergeyklay requested changes

2017-03-10 14:51 UTC, sergeyklay commented on tests/unit/Mvc/MicroTest.php
> +                $app->handle("/api");
```php
expect($micro->handle('/api'))->equals("success"); //❓ 
```

2017-04-12 06:16 UTC, sergeyklay commented
Fixed in the `3.2.x` branch. Thank you for contributing.

2017-04-12 06:16 UTC, closed without merging