[WIP]3.2.x paginator having
phalcon/cphalcon pull request #12712
Opened 2017-03-15 14:57 UTC by Jurigag

Hello!

* Type: bug fix | new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/12111

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: This is adding way to properly calculate pages and items when using having in builder.

Thanks

2017-03-23 12:46 UTC, Jurigag commented
rebased @sergeyklay

2017-03-28 16:17 UTC, Jurigag commented
@sergeyklay appveyor timed out

2017-03-28 19:34 UTC, sergeyklay requested changes

2017-03-28 19:34 UTC, sergeyklay commented on phalcon/paginator/adapter/querybuilder.zep
> +		    let row = db->fetchOne(sprintf("SELECT COUNT(*) as rowcount FROM (%s) as T1", sql["sql"]), Db::FETCH_ASSOC, sql["bind"]),
sprintf?

2017-03-28 19:44 UTC, Jurigag commented on phalcon/paginator/adapter/querybuilder.zep
> +		    let row = db->fetchOne(sprintf("SELECT COUNT(*) as rowcount FROM (%s) as T1", sql["sql"]), Db::FETCH_ASSOC, sql["bind"]),
It looks cleaner imho than:

`"SELECT COUNT(*) as rowcount FROM (" . sql["sql"] . " as T1"`

2017-03-28 19:45 UTC, sergeyklay commented on phalcon/paginator/adapter/querybuilder.zep
> +		    let row = db->fetchOne(sprintf("SELECT COUNT(*) as rowcount FROM (%s) as T1", sql["sql"]), Db::FETCH_ASSOC, sql["bind"]),
But slower

2017-03-28 19:50 UTC, Jurigag commented on phalcon/paginator/adapter/querybuilder.zep
> +		    let row = db->fetchOne(sprintf("SELECT COUNT(*) as rowcount FROM (%s) as T1", sql["sql"]), Db::FETCH_ASSOC, sql["bind"]),
Oh right, thought it could be somehow optimized, yea i will change it i guess.

2017-04-05 13:40 UTC, Jurigag commented
Removed sprintf @sergeyklay

2017-04-05 18:55 UTC, merged

2017-04-05 18:55 UTC, sergeyklay commented
Thank you