[WIP]Model hasChanged array
phalcon/cphalcon pull request #12713
Opened 2017-03-15 15:35 UTC by Jurigag

Hello!

* Type: bug fix | new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/12669

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: This is fixing issue as well adding option to check if array of fields was changed in models with ability to check if all provided fields were changed.

Thanks

2017-03-15 23:06 UTC, sergeyklay requested changes

2017-03-15 23:06 UTC, sergeyklay commented on phalcon/mvc/model.zep
> +	public function hasChanged(var fieldName = null, boolean allFields = false) -> boolean
Could you please amend PHPDoc with example and update CHANELOG.md?

2017-03-17 10:38 UTC, Jurigag commented on phalcon/mvc/model.zep
> +	public function hasChanged(var fieldName = null, boolean allFields = false) -> boolean
Yea i will update changelog once there will be 3.2.x branch cuz i will need to update it then anyway.

2017-03-23 12:46 UTC, Jurigag commented
rebased @sergeyklay

2017-03-23 16:11 UTC, sergeyklay requested changes
Could you please fix doc?

2017-03-23 16:11 UTC, sergeyklay commented on phalcon/mvc/model.zep
> +     * $hasChanged = $robot->hasChanged(["type", "name", true]); // returns false
```php
$robot->hasChanged(["type", "name"], true);
```

2017-03-23 16:30 UTC, Jurigag commented on phalcon/mvc/model.zep
> +     * $hasChanged = $robot->hasChanged(["type", "name", true]); // returns false
Oh, okay i see space.

2017-03-24 12:21 UTC, Jurigag commented
Fixed comment.

2017-04-27 14:54 UTC, Jurigag commented
Rebased @sergeyklay

2017-05-08 11:17 UTC, Jurigag commented
Rebased @phalcon/framework-team

2017-05-08 12:38 UTC, merged

2017-05-08 12:38 UTC, sergeyklay commented
Thank you