Remove php 7.1 from allowed failures
phalcon/cphalcon pull request #12747
Opened 2017-03-24 21:34 UTC by Jurigag

Hello!

* Type: code quality
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: This removes php 7.1 from allowed failures to test php 7.1

Thanks

2017-03-24 21:35 UTC, sergeyklay commented
Refs: https://github.com/phalcon/cphalcon/issues/12055

2017-03-24 21:36 UTC, Jurigag commented
And https://github.com/phalcon/zephir/pull/1415 too since ti's fixing 7.1

2017-03-24 23:23 UTC, sergeyklay commented
@Jurigag I will keep this open to testing 7.1. Feel free to commit here in order to restart build

2017-03-26 15:11 UTC, sergeyklay requested changes

2017-03-26 15:11 UTC, sergeyklay commented on phalcon/mvc/view/engine/volt.zep
> +	protected _macros = [];
PHP doesn't support default array values

https://github.com/phalcon/zephir/issues/1255

2017-03-26 15:14 UTC, Jurigag commented on phalcon/mvc/view/engine/volt.zep
> +	protected _macros = [];
So i need to set it in construct method perhaps?

2017-03-27 22:00 UTC, Jurigag commented
@sergeyklay ready to merge, will you merge ito 3.2.x or i should cherry pick it?

2017-03-27 22:10 UTC, sergeyklay commented
Could you cherry pick it please?

2017-03-27 23:27 UTC, merged

2017-03-27 23:27 UTC, sergeyklay commented
Thank you