Factory load for di
phalcon/cphalcon pull request #12776
Opened 2017-04-07 15:15 UTC by Jurigag

Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: I already introduced factory loaders, this is other way to have output as array to pass it to `Phalcon\Di::set()` as second parameter. Is returns array for complex service registration, so for example instead of:

```php
$di->set('db', Factory::load($config->database));
```

Which will create adapter object here

You can use:

```php
$di->set('db', Factory::loadForDi($config->database));
```

Which will create adapter object on `$di->get('db')`

Thanks

2017-04-08 19:34 UTC, Izopi4a commented
hmm nice 👍 

may I suggest adding something like 

```
function checkLoadArguments() { //or something like that i dont know. A bit tired atm
 if .. throw ...
}
```

so checking of parameters doesnt happen in two places `loadClass` and `LoadAsArray`

2017-04-08 20:07 UTC, Jurigag commented
@Izopi4a well good ideay, i will do it

2017-04-11 21:52 UTC, sergeyklay requested changes

2017-04-11 21:52 UTC, sergeyklay commented on phalcon/cache/backend/factory.zep
> +			if typeof frontend != "array" && !(frontend instanceof Config) {
frontend instanceof Config ?

2017-04-12 09:34 UTC, Jurigag commented on phalcon/cache/backend/factory.zep
> +			if typeof frontend != "array" && !(frontend instanceof Config) {
Oh right `config->toArray();` will just return array without config instances? My mistake then.

2017-04-27 21:14 UTC, Jurigag commented
Some weird random seg fault on php 5.6

2017-05-23 08:11 UTC, Jurigag commented
This is ready for mergei  guess.

2017-05-23 08:45 UTC, sergeyklay commented
@Jurigag I'm not sure about CHANGELOG.md. It seems to me it is outdated. Could you please rebase onto 3.2.x. Just to be sure that all ok

2017-05-23 08:54 UTC, Jurigag commented
Sure thing.

2017-05-23 09:02 UTC, merged

2017-05-23 09:02 UTC, sergeyklay commented
Thank you

2017-05-23 09:02 UTC, sergeyklay commented
Can you update the docs?