refs #11999 - Add the ability to use FrontendInterface to serialize M…
phalcon/cphalcon pull request #12808
Opened 2017-04-22 00:16 UTC by ogarbe

…odel and ResultSet

Hello!

* Type: new feature
* Link to issue: #11999 

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change: add FrontendInterface in DI (name "serializer") in order to serialize/unserialize Model, Collection, Resultset with a better thing than serialize/unserialize method

Thanks

2017-04-22 07:22 UTC, sergeyklay commented
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.2.x` branch?

2017-04-22 07:27 UTC, sergeyklay requested changes

2017-04-22 07:27 UTC, sergeyklay commented on phalcon/mvc/model/resultset/complex.zep
> +		let dependencyInjector = \Phalcon\DI::getDefault();
```zep
use Phalcon\Di;

// ...

let dependencyInjector = Di::getDefault();

if typeof dependencyInjector != "object" {

}
```

2017-04-22 07:27 UTC, sergeyklay commented on phalcon/mvc/model/resultset/complex.zep
> +		let dependencyInjector = \Phalcon\DI::getDefault();
The same here

2017-04-22 07:27 UTC, sergeyklay commented on phalcon/mvc/model/resultset/simple.zep
> +		let dependencyInjector = \Phalcon\DI::getDefault();
The same here

2017-04-22 07:27 UTC, sergeyklay commented on phalcon/mvc/model/resultset/simple.zep
> +		let dependencyInjector = \Phalcon\DI::getDefault();
the same here

2017-04-22 09:14 UTC, ogarbe commented
@sergeyklay CR done + PR changed

2017-04-22 21:08 UTC, sergeyklay submitted a review, later dismissed

2017-04-24 05:41 UTC, rrelenschi commented
Hello,

@sergeyklay , @ogarbe 
I've added a small change, to check that serializer is an object before using "instanceof" because calling instanceof on non-objects doesn't work.
Please review : https://github.com/phalcon/cphalcon/pull/12808/commits/c31caf01fbe39fc8df2108babd2208ee8ad36007
Thanks !

2017-04-24 08:07 UTC, ogarbe reviewed
ok for me

(i can't approve)

2017-06-19 08:35 UTC, ogarbe commented
Hello, why hasn't this been merged into 3.2 ? This feature increases a lot performances and has complete fallback !

2017-06-19 10:40 UTC, sergeyklay commented
@ogarbe Actually I can't merge this because this PR introduces segfaults. I'll tale a look later

2017-06-29 07:22 UTC, ogarbe commented
@sergeyklay any update please ?

2017-06-29 17:42 UTC, sergeyklay commented
@ogarbe Could you please separate this PR to few small PRs to detect the root of problem. Note: you have to use the 4.x branch

2017-06-29 17:56 UTC, virgofx commented
Model is already serializable... shouldn't need to do anything..

2017-06-30 07:23 UTC, ogarbe commented
@sergeyklay it was a small PR...

@virgofx yes it is, but it uses the PHP serializer and not the serializer we can define everywhere else in Phalcon... Hence poor performance (ig_serializer is 3 times faster...)

2017-08-01 07:29 UTC, ogarbe commented
@sergeyklay any help i can do in order to merge this for next release ?

2017-08-06 08:11 UTC, sergeyklay commented
@ogarbe It would be helpful to separate this PR into several small

2017-08-07 07:49 UTC, ogarbe commented
@sergeyklay i don't understand : the PR just 
- add a serializer in the DI
- use the serializer in model and resultset
- use the serializer in collection

What split would you like ? Adding the serializer without using it is a nonsense. Adding the serializer and using it for model but no resultset is also a nonsense. So i could split to remove collection, but i don't get what would be the use...

2017-08-07 08:17 UTC, sergeyklay commented
@ogarbe Do you know which change produce segfault? I mean file and line number. How are you going to find the issue?

2017-08-07 12:25 UTC, ogarbe commented
i'm not aware of any segfault, can you give me info about it, you told me this

``
@ogarbe Actually I can't merge this because this PR introduces segfaults. I'll take a look a bit later
--

and no more info. If you could tell me more, i would be able to.

2017-08-15 21:49 UTC, sergeyklay commented
@ogarbe 
As you can see this PR marked for the `4.0.x` branch. There is no reason to resolve this ASAP. The `3.2.x` branch only in the security support stage now.  So we don't plan to release `4.0.0` tomorrow or a mont or even in a month. Let me deal with this a bit later. In any case, thanks for your contribution and for the fact that you are so patiently ping me.

2017-12-27 14:19 UTC, ogarbe commented
@sergeyklay **9 month** after and this PR has not been looked at. It was ok on 3.1 than 3.2...

You rolled-out 3.3 which have new features (case / switch on volt) but not this one which increases performance on ALL storage on MVC requests.

What's the problem ?.

2018-01-01 09:29 UTC, sergeyklay commented
@ogarbe Thanks for the reminder. I apologize for completely overlooking this. Thank you for the PR. I know some people think this kinds of changes are trivial, but personally I believe it is important to get everything right, including tests and general design. There were some problems here and for a long time I couldn't make it work as expected. At least some tests constantly was failed. We can't accept new features in minor versions. Next major version is 4.0.0. Could you send your PR to the 4.0.x branch. So thanks again for this New Feature Request, and again I am sorry about the delay.

2018-02-16 14:13 UTC, ogarbe commented
@sergeyklay : PR updated to 4.0.0

2018-11-01 17:20 UTC, niden commented
@ogarbe Thank you for this. Sorry to be a pain, can you resolve the conflict please? Assigning this to me also so that I can check it out with @sergeyklay when he is available.

2018-11-05 18:15 UTC, sergeyklay commented
I canceled AppVeyor's build for this PR. No worries, I just need a spare build agent right now. I'll restart this build a bit later

2018-11-06 09:36 UTC, ogarbe commented
> @ogarbe Thank you for this. Sorry to be a pain, can you resolve the conflict please? Assigning this to me also so that I can check it out with @sergeyklay when he is available.

it's done @niden

2018-11-07 14:06 UTC, niden commented
@ogarbe One last thing please. Can you add a line to the `CHANGELOG-4` please regarding this feature?

This is solid.

2018-11-28 15:07 UTC, ogarbe commented
@niden : done

2018-11-29 00:22 UTC, niden approved these changes

2018-11-29 00:23 UTC, merged