Give different result from Resultset::delete() depending on success
phalcon/cphalcon pull request #12828
Opened 2017-04-28 12:48 UTC by 1RV34

Hello!

* Type: bug fix / new feature (unsure, it's unwanted behavior that is inconsistent with the behavior of `Model::delete()`)
* Link to issue: #11133

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change: When any `Model::delete()` fails the result bubbles to cause `ResultSet::delete()` to return `false` as well.

Thanks

2017-04-28 12:52 UTC, Jurigag commented
Update changelog also and add some simple test.

2017-04-30 15:46 UTC, sergeyklay approved these changes

2017-04-30 16:01 UTC, Jurigag requested changes
Update changelog, add test

2017-05-01 10:22 UTC, 1RV34 commented
I've added a message to the changelog but not sure if it's according to the standards that those messages should be.

Secondly, I'm not completely sure how to properly create a test for this. Basically if any of the `Model::delete()` calls that are made fails and causes a transaction rollback to happen the result should be `false` just like the `Model::delete()` result. Could I get some help with this?

2017-05-01 10:46 UTC, Jurigag commented on CHANGELOG.md
> +- Made `Resultset::delete()` return `false` when any of the `Model::delete` calls fails [PR #12828](https://github.com/phalcon/cphalcon/pull/12828) fixing [issue #11133](https://github.com/phalcon/cp
No need for link ot pr, just only add issue like other changes aboves. Also without "issue"

2017-05-01 10:47 UTC, Jurigag commented
About test - just return some random false in some of model::delete, then check if result returned by resultset->delete is false.

2017-05-01 18:44 UTC, sergeyklay commented
Just updated CHANGELOG

2017-05-13 09:16 UTC, sergeyklay approved these changes

2017-05-13 09:26 UTC, merged

2017-05-13 09:26 UTC, sergeyklay commented
Thank you