Adding hasFunction Method
phalcon/cphalcon pull request #12841
Opened 2017-05-10 01:16 UTC by Fenikkusu

Hello!

* Type:  new feature
* Link to issue: NA

**In raising this pull request, I confirm the following (please check boxes):**

- [ ] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [ ] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

In many of my projects, I find myself constantly adding PHP Internal Functions to the Volt Compiler Engine (IE: substr). I found this very repetitive and frustrating to have to add to all of them. With this in mind, I've updated the compiler to have a new option of 'includePhpFunctions'. When _compileSource is ran, it looks for this option and automatically registers all php internal functions within the compiler. To maintain existing code bases, I've added a hasFunction method which I use in the function loop such that it only adds it if it wasn't previously added.

Thanks

2017-05-10 08:56 UTC, Jurigag commented on phalcon/mvc/view/engine/volt/compiler.zep
> +                let includePhpFunctions = options["includePhpFunctions"];
How about make it possible to select which exactly php functions we want to include? Just accept boolean or array maybe?

2017-05-12 00:17 UTC, Fenikkusu commented on phalcon/mvc/view/engine/volt/compiler.zep
> +                    throw new Exception("'compileAlways' must be a bool value");
Oops...Error Mistake

2017-05-12 00:20 UTC, Fenikkusu commented on phalcon/mvc/view/engine/volt/compiler.zep
> +                let includePhpFunctions = options["includePhpFunctions"];
Well technically I wouldn't really need to use function_exists. Just loop through the list of functions. If not set from the option, set default to be actual functions. I see no reason as why not...

2017-05-12 05:17 UTC, Jurigag commented on phalcon/mvc/view/engine/volt/compiler.zep
> +                let includePhpFunctions = options["includePhpFunctions"];
Because someone could provie wrong, non existing function name.

2017-05-25 23:51 UTC, Fenikkusu commented
I've added the new updates. You can pass either and array or true. @sergeyklay, a question for you. When running 'function_exists' on 'substr', I kept getting false. After looking at the compiled code, I found that function_exists was being changed to zephir_function_exists. I got around it by using call_user_func instead of function_exists. Does this seem like the valid way to do this, or is it possible that zephir_function_exists wasn't working correctly?

Also, not sure what's going on with failures in Travis.

2017-05-26 08:57 UTC, sergeyklay commented
@Fenikkusu We'll double check `zephir_function_exists` asap. 

Cc: @sjinks

2017-05-26 09:11 UTC, Jurigag commented
Failures on travis are codeception bug, you will need to cherry pick some commit from @sergeyklay repo

2017-05-26 09:12 UTC, sergeyklay commented
https://github.com/phalcon/cphalcon/pull/12861

2017-07-22 14:07 UTC, sergeyklay commented
@Fenikkusu  The `zephir_function_exists ` function  has been fix in the latest Zephir

2017-07-22 14:12 UTC, sergeyklay requested changes

2017-07-22 14:12 UTC, sergeyklay commented on phalcon/mvc/view/engine/volt/compiler.zep
> +                    throw new Exception("'includePhpFunctions' must be a bool or array value");
```zep
"The 'includePhpFunctions' option must be be either a bool or array"
```

2017-07-22 14:12 UTC, sergeyklay commented on phalcon/mvc/view/engine/volt/compiler.zep
> +        let includePhpFunctions = false;
Could you please you the same indents in the whole file?

2017-09-24 23:10 UTC, sergeyklay commented
@Fenikkusu ping

2018-05-27 22:35 UTC, closed without merging