3.2.x Grouped Config
phalcon/cphalcon pull request #12884
Opened 2017-06-07 01:47 UTC by Fenikkusu

Hello!

* Type: new feature
* Link to issue: NA

**In raising this pull request, I confirm the following (please check boxes):**

- [ ] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [ ] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

Many systems use the concept of distribution config files where config.conf is added to the repo but config.dist.conf is ignored. These changes allow us to easily accomplish the same concept in Phalcon. Additionally, this leverages the existing Config Factory to allow us to combine either a specifc adapter or multiple different adapters.

```php
$configFiles = [
  [
    'adapter' => 'ini', //This specifically uses the ini adapter.
    'filePath' => '/usr/www/conf.ini'
  ],
  __DIR__ . '/etc/config.json' //This will use the default adapter.
];

if (file_exists([__DIR__ . '/etc/config.dist.json']) {
    $configFiles[] = __DIR__ . '/etc/config.dist.json'; //This will use the default adapter.
}

$configFiles[] = [
  'adapter' => 'array', //This will use the traditional \Phalcon\Config object.
  'config'   => [
    'debug' => true
  ]
];

//Initialize Config using the Json adapter as the default.
$config = new \Phalcon\Config\Adapter\Grouped($configFiles, 'json');
```

Thanks

2017-06-07 09:56 UTC, sergeyklay commented
Could you please update the CHANGELOG.md

2017-06-07 09:57 UTC, sergeyklay commented on phalcon/config/adapter/grouped.zep
> + *            "adapter"  => "php""path/to/config.dist.php"
`"adapter"  => "php""path/to/config.dist.php"` => `"adapter"  => "php"`

2017-06-07 09:59 UTC, sergeyklay requested changes

2017-06-07 09:59 UTC, sergeyklay commented on phalcon/config/adapter/grouped.zep
> +		    } elseif !isset(configInstance["adapter"]) {
`!isset(configInstance["adapter"])` => `!isset configInstance["adapter"]`

2017-06-07 09:59 UTC, sergeyklay commented on phalcon/config/adapter/grouped.zep
> +                if !isset(configInstance["config"]) {
the same

2017-06-07 09:59 UTC, sergeyklay commented on tests/unit/Config/Adapter/GroupTest.php
> + */
could you please remove this

2017-06-17 15:55 UTC, Fenikkusu commented
Changes Applied

2017-06-17 22:42 UTC, merged

2017-06-17 22:42 UTC, sergeyklay commented
Thank you