Added describeReferences method in postgresql DB
phalcon/cphalcon pull request #12956
Opened 2017-07-12 13:09 UTC by sergeysviridenko

Hello!

* Type: bug fix
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
Added describeReferences method in adapter and changed describeReferences method in dialect for postgresql DB

Thanks

2017-07-17 09:11 UTC, sergeyklay requested changes

2017-07-17 09:11 UTC, sergeyklay commented on phalcon/db/adapter/pdo/postgresql.zep
> +        	public function describeReferences(string! table, string! schema = null) -> <Reference[]>
```zep
use Phalcon\Db\Reference;

// ...

public function describeReferences(string! table, string! schema = null) -> <Reference[]>
```

2017-07-17 09:11 UTC, sergeyklay commented on phalcon/db/adapter/pdo/postgresql.zep
> +        	 * Lists table references
Could you please fix indents?

2017-07-17 11:06 UTC, sergeyklay requested changes

2017-07-17 11:06 UTC, sergeyklay commented on phalcon/db/dialect/postgresql.zep
> +				  AND ";
Could you please fix tests here?

2017-07-18 13:51 UTC, sergeyklay requested changes

2017-07-18 13:51 UTC, sergeyklay commented on phalcon/db/adapter/pdo/postgresql.zep
> +use Phalcon\Db\Reference;
```zep
use Phalcon\Db\ReferenceInterface;
```

2017-07-18 13:51 UTC, sergeyklay commented on phalcon/db/adapter/pdo/postgresql.zep
> +	public function describeReferences(string! table, string! schema = null) -> <Reference[]>
```diff
- public function describeReferences(string! table, string! schema = null) -> <Reference[]>
+ public function describeReferences(string! table, string! schema = null) -> < ReferenceInterface[]>
```

2017-07-18 13:51 UTC, sergeyklay commented on phalcon/db/dialect/postgresql.zep
> +		var sql = "
Use single line here to avoid indents issue.

2017-07-18 13:51 UTC, sergeyklay commented on phalcon/db/dialect/postgresql.zep
> +		var sql = "
![esvtpcxuqweghsxycmff7a](https://user-images.githubusercontent.com/1256298/28320402-2f6779d0-6bd9-11e7-90a7-1fc59eef49b0.png)

2017-07-18 15:04 UTC, tztztztz commented
Please sync it with https://github.com/phalcon/cphalcon/pull/12962

2017-07-18 16:33 UTC, closed without merging

2017-07-18 17:57 UTC, sergeysviridenko commented
@tztztztz We're solving different issue and changing different methods. new request #12969