Prevent invalid element name
phalcon/cphalcon pull request #12954
Opened 2017-07-11 23:18 UTC by emiliodeg

Prevent create form element with empty name value like ''

Hello!

* Type: bug fix
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

Thanks

2017-07-17 13:52 UTC, sergeyklay requested changes

2017-07-17 13:52 UTC, sergeyklay commented on phalcon/forms/element.zep
> +			throw new \InvalidArgumentException('Form element name is required');
`throw new \InvalidArgumentException('...');` **=>**`throw new \InvalidArgumentException("...");`

2017-07-17 13:55 UTC, sergeyklay commented
@emiliodeg What do you want to fix? Could you please describe a bit more the issue? Also can you  create a small test which will cover code you have changed? Thank you for contributing.

2017-07-18 21:03 UTC, emiliodeg commented
Hi @sergeyklay I trying to prevent this posible error

```php 
new \Phalcon\Form\Element\Text(''); // empty name
new \Phalcon\Form\Element\TextArea('      '); // empty name
```

2017-07-19 05:14 UTC, sergeyklay commented
@emiliodeg Anyway you have to use `" "` instead of `' '`.

2017-07-22 06:27 UTC, sergeyklay approved these changes
@emiliodeg Looks good to me. Could you please update the CHANGELOG.md

2017-08-06 08:37 UTC, merged