Followup for #12564 added transaction to param in model::find() and model::findFirst()
phalcon/cphalcon pull request #13097
Opened 2017-09-28 14:32 UTC by chilimatic

Hello!

* Type: bug fix | new feature | code quality | documentation
* Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

This change is to achieve the following

In Unit-testing one usual procedure is to create a transaction for a TestCase and after the execution rollback this change. 

Which means there is a "long transaction" going on and we want to check if the transaction actually is writing the correct values in the database. But the static context of model::find / model::findFirst does not get the transaction passed.

To achieve that passing a new index "transaction" containing an transaction in the $param array seams to be a viable solution. 

Another use-case can be having multiple transactions and wanting to look inside. 

Just to be precise -> ofc we could just get the connection and query manually inside of it, but I want to be as close to the framework as possible when testing certain services hence I want to use the model. 

I took your reviews and advice from the last attempt and used the params to not break the interfaces / change method signatures.  

the logic is implemented as follows: 

if you pass in a transaction via param in the find/findFirst method. It will set the transaction to query object and this transaction will be used for all queries and executions within this query context.

This should not affect any standard behaviour but still allow me to finally achieve cleaner unittests for my usecase.

I still owe you some unitests, but please look through it first so it's not after several hours of refactoring and cleanups that this gets rejected.

2017-10-09 09:44 UTC, chilimatic commented
@sergeyklay any feedback on the functional code implementation ? if it looks okay to you we can move the semantics and syntaxation discussion and I will start writing tests for it.

2017-10-09 10:46 UTC, sergeyklay requested changes

2017-10-09 10:46 UTC, sergeyklay commented on phalcon/mvc/model/query.zep
> +			if (connection !== null) {
```zep
if typeof connection == "object"
```

2017-10-10 23:17 UTC, chilimatic commented
I did a force push to add the ticket reference correctly to all the commits

2017-10-11 13:01 UTC, sergeyklay approved these changes
LGTM

2017-10-11 13:09 UTC, chilimatic commented
@sergeyklay thx,  I will write the unitests now :)

2017-11-02 12:18 UTC, sergeyklay commented
@chilimatic Could you please use 3.3.x branch for that

2017-11-02 12:23 UTC, chilimatic commented
@sergeyklay ofc, rebase my changes onto 3.3.x ?

2017-11-03 16:22 UTC, sergeyklay commented
The 3.3.x branch is upstream for now

2017-11-03 16:27 UTC, chilimatic commented
I will try to finish this asap. I just have some project deadlines comming up

2017-12-18 12:39 UTC, chilimatic commented
added new issue #13226  and PR #13227

2017-12-18 12:39 UTC, closed without merging