* add function hasHeader to request
phalcon/cphalcon pull request #13136
Opened 2017-10-26 13:07 UTC by limingxinleo

Hello!

* Type: new feature

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

When I use getHeader to take some value out of headers, those the value don't exist,I will get empty string. But I expect it is null. So I add a function, called hasHeader to solve the problem.

Thanks

2017-10-26 14:10 UTC, sergeyklay requested changes
looks good to me. Could you please fix PSR issue

2017-10-26 14:10 UTC, sergeyklay commented on tests/unit/Http/RequestTest.php
> +            }
```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 136 | ERROR | [x] Function closing brace must go on the next line
     |       |     following the body; found 1 blank lines before brace
     |       |     (PSR2.Methods.FunctionClosingBrace.SpacingBeforeClose)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

2017-10-26 14:18 UTC, limingxinleo commented
Thanks for your reply,I have fixed the PSR issue.

2017-10-26 17:15 UTC, sergeyklay commented
@limingxinleo 
I will keep this open for a day or two to allow other contributors a chance to speak up, and to take a fresh look at it later. But at the moment it seems good to me. 

P.S. Update please the change log

2017-10-26 17:16 UTC, sergeyklay commented
cc: @phalcon/core-team @phalcon/collaborators

2017-10-26 17:16 UTC, sergeyklay approved these changes

2017-10-29 22:25 UTC, Jurigag commented on CHANGELOG-3.3.md
> +- Added function hasHeader to `Phalcon\Http\Request`
Better:

```
`Added `Phalcon\Http\Request::hasHeader` to check if certain header exists`
```

2017-10-30 10:37 UTC, limingxinleo commented on CHANGELOG-3.3.md
> +- Added function hasHeader to `Phalcon\Http\Request`
thanks

2017-10-30 10:48 UTC, merged

2017-10-30 10:48 UTC, sergeyklay commented
Thank you