Bugfix/db adapater binded objects
phalcon/cphalcon pull request #13561
Opened 2018-10-31 12:16 UTC by CameronHall

Hello!

* Type: bug fix
* Link to issue: https://github.com/phalcon/cphalcon/issues/13058

**In raising this pull request, I confirm the following (please check boxes):**

- [X ] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [ X] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change: Fixed missing placeholder creation when objects `__toString` method are invoked.

Thanks

2018-11-01 17:09 UTC, niden commented
@CameronHall Could you please add a test or two for this? I am having trouble understanding this change because of the structure of the IF statements.

2018-11-01 17:10 UTC, niden requested changes
Test requested

2018-11-02 00:11 UTC, CameronHall commented
@niden no worries. I'll try and work out why the Travis tests are failing first then I'll get back to you with the test :)

2018-11-07 10:18 UTC, CameronHall commented
The tests have been added :)

2018-11-07 16:33 UTC, niden commented
@CameronHall One more request please. Can you add a line to the changelog regarding this?

2018-11-07 17:31 UTC, sergeyklay submitted a review, later dismissed
LGTM

2018-11-07 21:04 UTC, niden commented
And we will need a separate PR for the `v4` branch please :)

2018-11-07 22:31 UTC, CameronHall commented
Changelog has been updated and I've created a PR for 4.0 :) https://github.com/phalcon/cphalcon/pull/13584

2018-11-07 23:09 UTC, niden approved these changes

2018-11-07 23:09 UTC, merged

2018-11-07 23:09 UTC, niden commented
@CameronHall Thank you for the contribution!

2018-11-14 14:40 UTC, niden commented
Closing - Thanks @CameronHall