[NFR] Added events response:beforeSendHeaders, response:afterSendHeaders
phalcon/cphalcon pull request #13620
Opened 2018-11-27 13:47 UTC by CameronHall

Hello!

* Type: new feature
* Link to issue: #10689
* Link to existing PR: https://github.com/phalcon/cphalcon/pull/10884

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: Updated existing pull request to 4.0.x branch. >>Added events `response:beforeSendHeaders` and `response:afterSendHeaders` to `Phalcon\Http`Response`

Thanks

2018-12-05 03:02 UTC, niden commented
Same here: please rebase

2018-12-05 03:02 UTC, niden commented
Same here: please rebase

2018-12-08 04:19 UTC, CameronHall commented
All done @niden

2018-12-08 15:29 UTC, niden requested changes

2018-12-09 15:58 UTC, niden submitted a review, later dismissed

2018-12-09 22:30 UTC, niden approved these changes

2018-12-09 22:31 UTC, merged