Full support of PHP 7.3 for 4.0.x
phalcon/cphalcon pull request #13622
Opened 2018-11-27 22:53 UTC by CameronHall

Full support of PHP 7.3
Fixes: #13288, #12176, #12385, #12648, #12705

2018-11-27 22:58 UTC, sergeyklay approved these changes

2018-11-27 23:39 UTC, sergeyklay requested changes

2018-11-27 23:39 UTC, sergeyklay commented on tests/unit/Mvc/ViewTest.php
> +                } catch (\PHPUnit_Framework_Exception $e) {
```suggestion
                } catch (\PHPUnit\Framework\Exception $e) {
```

2018-11-27 23:40 UTC, sergeyklay commented on tests/unit/Mvc/ViewTest.php
> +                } catch (\PHPUnit_Framework_Exception $e) {
@CameronHall It seems this is the cause of the failing test

2018-11-28 00:17 UTC, CameronHall commented
Looks like it passed this time @sergeyklay

2018-11-28 05:09 UTC, merged

2018-11-28 05:09 UTC, sergeyklay commented
Thank you