T12098 remove deprecated code
phalcon/cphalcon pull request #13641
Opened 2018-12-08 01:44 UTC by niden

Hello!

* Type: code quality
* Link to issue: #12098 

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Removed deprecated code based on the list

Thanks

2018-12-08 01:45 UTC, niden commented
cc @sergeyklay

2018-12-09 23:16 UTC, sergeyklay requested changes
Some minor changes

2018-12-09 23:16 UTC, sergeyklay commented on CHANGELOG-4.0.md
> +- Removed deprecated `Phalcon\Paginator\Adapter\QueryBuilder - total_pages`
Could you please use common format for vars:
```
Phalcon\Paginator\Adapter\QueryBuilder::$total_pages
```

2018-12-09 23:16 UTC, sergeyklay commented on CHANGELOG-4.0.md
> +- Removed deprecated `Phalcon\Paginator\Adapter\Model::getPaginate()`
Could you please use common format for methods:
```
Phalcon\Paginator\Adapter\QueryBuilder::getPaginate
```

2018-12-09 23:16 UTC, sergeyklay commented on CHANGELOG-4.0.md
> +- Removed `memcache` support from adapters (use `libmemcached`)
Is there any issue/PR we can mention here and below for each of change log entry?

2018-12-09 23:16 UTC, sergeyklay commented on phalcon/mvc/micro/lazyloader.zep
> +	public function callMethod(string! method, arguments, <BinderInterface> modelBinder = null)
Is there issue where we decided to remove `__call`

2018-12-10 01:19 UTC, sergeyklay approved these changes

2018-12-10 01:23 UTC, merged