Security Token Retention [PR#12518] and Fixed Security Tests
phalcon/cphalcon pull request #13642
Opened 2018-12-08 14:24 UTC by CameronHall

Hello!

* Type: cherry-picked existing PR
* Link to PR: [#12518](https://github.com/phalcon/cphalcon/pull/12518)

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change: Created a retainer for the current session token in order to not break checkToken functionality if getToken is called before. Also fixed the security tests segmentation faults.

Thanks

2018-12-08 15:18 UTC, niden requested changes

2018-12-08 15:18 UTC, niden commented on phalcon/security.zep
> +			let userToken = (string) request->getPost(tokenKey);
Can you change this to:

`let userToken = request->getPost(tokenKey, "string");`

Direct casting is faster for sure but I prefer passing the token here via the sanitization/filter

2018-12-08 22:02 UTC, CameronHall commented
All done @niden

2018-12-08 22:12 UTC, niden approved these changes

2018-12-09 15:39 UTC, merged

2018-12-09 15:39 UTC, niden commented
Thank you!