T12921 remove session from di factory
phalcon/cphalcon pull request #13667
Opened 2018-12-17 20:31 UTC by niden

Hello!

* Type: new feature
* Link to issue: #12921 

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Removed the `session` service from the `FactoryDefault` container

Thanks

2018-12-17 21:16 UTC, niden commented
cc @sergeyklay

2018-12-17 22:15 UTC, sergeyklay requested changes
There was 1 failure:
```
Phalcon\Test\Unit\Di\FactoryDefault\ConstructCest::diFactoryDefaultConstructServices
```

> Failed asserting that 19 matches expected 21

2018-12-17 22:22 UTC, sergeyklay requested changes

2018-12-17 22:22 UTC, sergeyklay commented on CHANGELOG-4.0.md
> +- Changed `Phalcon\DI\FactoryDefault` to not load the `Phalcon\Session\Adapter\Files` using the name `session` by default [#12921](https://github.com/phalcon/cphalcon/issues/12921)
```suggestion
- Changed `Phalcon\DI\FactoryDefault` to not load by default
    - the `Phalcon\Session\Adapter\Files` using the name `session` 
    - the `Phalcon\Session\Bag` using the name `sessionBag` 
  [#12921](https://github.com/phalcon/cphalcon/issues/12921)
```

2018-12-18 00:57 UTC, niden commented
@sergeyklay fixed issues

2018-12-18 05:35 UTC, sergeyklay approved these changes

2018-12-18 13:43 UTC, merged