Tests for Cli/Console
phalcon/cphalcon pull request #13719
Opened 2018-12-28 21:17 UTC by npfedwards

Hello!

* Type: code quality
* Link to issue: https://github.com/phalcon/cphalcon/issues/13654

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)?
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:
Added new tests for the missing ones for Cli/Console (learned a lot on the way). This includes a minor fix where console->handle() wasn't letting the dispatcher know which module it had used so the test was failing and a readme tweak.

A few caveats
* Should the line HandleCest.php:151 be required to make it work? ```$console->dispatcher->setNamespaceName("Phalcon\\Test\\Modules\\Backend\\Tasks");``` seems odd behaviour to me.
* I didn't know what the convention was with docblocks and authors (I haven't read enough of the code), so I added my name below Phalcon Team so you know who to blame, I can change that if that is wrong.
* I don't know how code coverage is tested/where the results are so I didn't check that I've tested everything.

Thanks

2018-12-28 21:46 UTC, npfedwards commented
I'll look into why these tests are failing, seems to be unrelated to the changes I made, but I may be wrong.

2018-12-29 05:46 UTC, ruudboon commented
@npfedwards I see some styling errors in the test. Did you try running **phpcs** on the changed files?And on error fix them with **phpcbf**

2018-12-30 19:39 UTC, niden commented
@npfedwards Add the `editorconfig` plugin for storm and you will have no problems after that. It will detect tabs for zep files and spaces for php :)

2018-12-31 09:10 UTC, npfedwards commented
Thanks @niden. I'm on holiday for the next few days but will be working out why my tests had weird side effects after that.

2019-01-03 22:38 UTC, niden commented
@npfedwards I hope you had a nice break  :)

From what I see in the log all you will have to do is to run `phpcbf` in your nanobox environment and that should fix the issue that makes the build fail

2019-01-04 16:59 UTC, npfedwards commented
@niden I actually have some failing tests (nothing to do with the ones I've written). For example the session tests all seem to fail now. I might have an idea that some output isn't caught by the output buffer - hence session can't start.

2019-01-06 20:46 UTC, npfedwards commented
Just added a fix and test for #13724 because I needed some of the fixtures I'd written in this PR to test it.

2019-01-10 21:52 UTC, niden requested changes
This looks great!! Thank you so much.

A couple of comments. Also please add an entry to the CHANGELOG for the change in `console.zep`

2019-01-10 21:52 UTC, niden commented on tests/cli/Cli/Console/HandleCest.php
> +                    "path" => __DIR__ . "/../../../_data/fixtures/modules/frontend/Module.php",
Can we use `dataFolder()`  here instead of the `__DIR__` etc.?

2019-01-10 21:52 UTC, niden commented on tests/cli/Cli/Console/HandleCest.php
> +                    "path" => __DIR__ . "/../../../_data/fixtures/modules/backend/Module.php",
Same

2019-01-10 21:52 UTC, niden commented on tests/cli/Cli/Console/HandleCest.php
> +                    "path" => __DIR__ . "/../../../_data/fixtures/modules/frontend/Module.php",
Same

2019-01-10 21:52 UTC, niden commented on tests/cli/Cli/Console/HandleCest.php
> +    public function cliConsoleHandleEvents(CliTester $I)
I would like to split this test into smaller ones if possible. It makes it easier to figure out what is tested and where. 

Perhaps create something in the lines of 

`cliConsoleHandleEventBoot`
`cliConsoleHandleEventBeforeStartModule`
etc.

2019-01-10 21:52 UTC, niden commented on tests/cli/Cli/Console/HandleCest.php
> +                    "path" => __DIR__ . "/../../../_data/fixtures/modules/backend/Module.php",
Same here for `dataFolder()`

2019-01-10 22:23 UTC, npfedwards commented
@niden Et voila

2019-01-10 22:45 UTC, merged

2019-01-10 22:46 UTC, niden commented
@npfedwards Thank you!!