Allow Config::merge to accept a basic array.
phalcon/cphalcon pull request #13830
Opened 2019-02-15 02:24 UTC by dschissler

I created a new clean PR with the alternate option that I presented in the last PR.  This will sit here for a few days until I have time to do the change log and to see about augmenting the tests.

ps. I wrote a metric shit load of zephir code today.

2019-02-15 03:41 UTC, niden requested changes
@dschissler This is solid. Can you please write a test and update the changelog?

2019-02-15 11:26 UTC, dschissler commented
@niden Absolutely but I'll do it probably tomorrow.

2019-02-15 16:02 UTC, sergeyklay commented on phalcon/config.zep
> +				throw new \Exception("Invalid data type for merge.");
Phalcon\Config\Exception

2019-02-15 16:38 UTC, niden commented on phalcon/config.zep
> +				throw new \Exception("Invalid data type for merge.");
Yes and this one! Sorry missed it

2019-02-15 22:06 UTC, dschissler commented
So I wrote a test but I don't know what in the hell I'm doing.  I tried to run the tests on the command line but it failed out with other stuff.  Maybe it works, I have no idea.  It would be nice if there was something brain dead like `./run-tests`.

2019-02-16 03:37 UTC, dschissler commented
@niden So it looks like new tests passed.  I wrote the logic correctly without being able to test it but then I forgot to add the stupid trait declaration and then the namespace use.  Do you want to take this or should I redo it to be less commits?  I still don't know how to run the tests from within my preferred VM.

2019-02-16 14:28 UTC, niden approved these changes

2019-02-16 14:31 UTC, merged

2019-02-16 14:31 UTC, niden commented
Thank you @dschissler

2019-02-16 14:34 UTC, dschissler commented
@niden np.  I have a question.  Do all of the commits get flattened into a single commit when you merge it?

2019-02-16 15:26 UTC, niden commented
@dschissler As a general rule (self imposed) we use the squash and merge option when merging.

2019-02-17 00:38 UTC, dschissler commented
@niden That is good to know.  Then I can just keep screwing with it until I get it right.

2019-02-17 01:24 UTC, niden commented
@dschissler Honestly I still haven't sat down to read how to squash stuff on my local repo, so I do it here on github. ;)