[NFR] - added description property to Cli\Router\Route
phalcon/cphalcon pull request #13936
Opened 2019-04-02 12:24 UTC by ekmst

Hello!

* Type: new feature
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Small description of change: added description property to Cli\Router\Route

## Usage: 
```php
$router = new \Phalcon\Cli\Router(false);
$router->add('test')->setName('testName')->setDescription('testDescription');
$router->add('test1')->setName('testName1')->setDescription('testDescription1');
$router->add('test2')->setName('testName2')->setDescription('testDescription2');

foreach ($router->getRoutes() as $route) {
    printf("%s    %s<br>\n", $route->getName(), $route->getDescription());
}
```

```
$./phalconcli
Available command or tasks:
   testName      testDescription
   testName1     testDescription
   testName2     testDescription
```
Thanks

2019-04-02 12:33 UTC, Jeckerson commented on tests/cli/Cli/Router/Route/GetDescriptionCest.php
> +            'test' => 'test description',
Make sense to move that array to dataProvider method.

2019-04-02 12:34 UTC, Jeckerson commented on tests/cli/Cli/Router/Route/SetDescriptionCest.php
> +            'test' => 'test description',
Make sense to move that array to dataProvider method.

2019-04-02 12:41 UTC, ekmst commented
@Jeckerson done

2019-04-02 21:19 UTC, sergeyklay submitted a review, later dismissed

2019-04-02 21:25 UTC, Jeckerson submitted a review, later dismissed

2019-04-04 14:38 UTC, niden requested changes

2019-04-04 14:38 UTC, niden commented on phalcon/Cli/Router/RouteInterface.zep
> +    public function setName(string name) -> <Route>;
Shouldn't this be `<RouteInterface>`?

2019-04-04 14:38 UTC, niden commented on phalcon/Cli/Router/Route.zep
> +    public function setDescription(string! description) -> <Route>
Same here these need to be `RouteInterface` (for `setName()` also)

2019-04-04 21:25 UTC, sergeyklay approved these changes

2019-04-05 09:01 UTC, Jeckerson approved these changes

2019-04-05 14:04 UTC, merged

2019-04-05 14:04 UTC, niden commented
Thank you @ekmst