New Attributes & Form attributes
phalcon/cphalcon pull request #14073
Opened 2019-05-14 14:27 UTC by emiliodeg

Implemented in Form
Changed CHANGELOG
Added tests

Hello!

Type: new feature
Link to issue: #13646

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I updated the CHANGELOG

Small description of change:
I created a new interface for HTML Attributes and I implemented in Form
I replaced the action property insteand of attributes
I writed tests
Thanks

2019-05-14 19:23 UTC, sergeyklay requested changes

2019-05-14 19:23 UTC, sergeyklay commented on tests/integration/Forms/FormCest.php
> +        $I->assertEquals($expected, $actual);
Phalcon\Messages\Messages Object (...) does not match expected type "array"

2019-05-15 02:11 UTC, niden commented
@emiliodeg If you can rebase this and check on the tests that would be great. Thanks

2019-05-15 15:21 UTC, emiliodeg commented
How can I rebase? I just only see merge

2019-05-15 15:40 UTC, Jurigag commented
In git.

2019-05-15 16:09 UTC, niden commented
@emiliodeg I will rebase that for you if you don't know. Have a look at Travis so that this passes and then I will merge it.

2019-05-16 00:03 UTC, niden commented
Closing in favor of https://github.com/phalcon/cphalcon/pull/14082

2019-05-16 00:03 UTC, closed without merging