Update PSR v0.6.1 #14118
phalcon/cphalcon pull request #14119
Opened 2019-05-23 11:26 UTC by emiliodeg

Hello!

* Type: update
* Link to issue:  #14118 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:
Changed PSR version from v0.6.0 to v0.6.1
Thanks

2019-05-23 12:50 UTC, niden commented
I had this issue before. Local/nanobox needs 0.6.1 which is the latest version. However when the code goes to Travis it complains about the version and can only work with 0.6.0

@sergeyklay any thoughts on this?

2019-05-23 20:25 UTC, zsilbi commented
I changed it to `^0.6` in my local config.

2019-05-25 20:55 UTC, sergeyklay requested changes

2019-05-25 20:55 UTC, sergeyklay commented on composer.json
> +    "ext-psr": "0.6.1",
```suggestion
    "ext-psr": "^0.6",
```

2019-05-25 21:15 UTC, sergeyklay approved these changes

2019-05-25 22:34 UTC, merged

2019-05-25 22:34 UTC, sergeyklay commented
Thank you