Added namespaces to some test fixtures.
phalcon/cphalcon pull request #14164
Opened 2019-06-06 00:52 UTC by SidRoberts

Hello!

* Type: code quality
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [-] I wrote some tests for this PR
- [-] I have updated the relevant CHANGELOG
- [-] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

I've purposely left the Annotations classes and the Tasks as some of them require no namespace.

2019-06-06 17:47 UTC, niden requested changes

2019-06-06 17:47 UTC, niden commented on tests/_data/fixtures/Di/services.php
> +        'className' => SomeComponent::class,
We needed that to be a single class that has been `required` hence no namespace for this.

2019-06-06 17:47 UTC, niden commented on tests/_data/fixtures/Di/services.yml
> +    className: \Phalcon\Test\Fixtures\Di\SomeComponent
same here

2019-06-06 23:43 UTC, SidRoberts commented
I've removed the DI stuff so it should be good to go once the build has completed.

2019-06-09 00:11 UTC, niden approved these changes

2019-06-09 00:11 UTC, merged

2019-06-09 00:11 UTC, niden commented
Thank you @SidRoberts