Get URL path only from the REQUEST_URI
phalcon/cphalcon pull request #14337
Opened 2019-08-27 15:29 UTC by scrnjakovic

Hi

* Type: new feature | code quality | documentation

Small description of change:

I added boolean flag to `Phalcon\Http\Request::getURI()` which if true, would have the query part omitted from the response. Flag is optional and set to false by default for backward compatibility.

Thanks

2019-08-28 05:31 UTC, CameronHall submitted a review, later dismissed

2019-08-28 09:52 UTC, sergeyklay requested changes

2019-08-28 09:52 UTC, sergeyklay commented on CHANGELOG-4.0.md
> +- Added optional boolean parameter to `Phalcon\Http\Request::getURI()` which indicates whether or not the method should return only the path without the query string
Could you use `## Added` section ?

2019-08-28 09:52 UTC, sergeyklay commented on phalcon/Http/Request.zep
> +    final public function getURI(bool onlyPath = false) -> string
Method `Request::getURI` should math `RequestInterface::getURI`

2019-08-28 14:49 UTC, scrnjakovic commented
Will fix these today when I get my hands on my pc.

On Aug 28, 2019, at 11:53, Serghei Iakovlev <notifications@github.com<mailto:notifications@github.com>> wrote:


@sergeyklay requested changes on this pull request.

________________________________

In CHANGELOG-4.0.md<https://github.com/phalcon/cphalcon/pull/14337#discussion_r318491558>:

> @@ -1,5 +1,6 @@
 # [4.0.0](https://github.com/phalcon/cphalcon/releases/tag/v4.0.0) (2019-xx-xx)
 ## Changed
+- Added optional boolean parameter to `Phalcon\Http\Request::getURI()` which indicates whether or not the method should return only the path without the query string


Could you use ## Added section ?

________________________________

In phalcon/Http/Request.zep<https://github.com/phalcon/cphalcon/pull/14337#discussion_r318492116>:

>       */
-    final public function getURI() -> string
+    final public function getURI(bool onlyPath = false) -> string


Method Request::getURI should math RequestInterface::getURI

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/phalcon/cphalcon/pull/14337?email_source=notifications&email_token=AA5YOQBT2LGHW4PPYOTZWK3QGZDJRA5CNFSM4IQF4BSKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCC5VZEQ#pullrequestreview-280714386>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AA5YOQCKYJ5VPCOWGY2USA3QGZDJRANCNFSM4IQF4BSA>.

2019-08-29 02:08 UTC, CameronHall requested changes

2019-08-29 02:08 UTC, CameronHall commented on phalcon/Http/Request.zep
> +	 * @return string
Looks like a combination of tabs and spaces mixing up that last part of the docblock.

2019-08-29 02:08 UTC, CameronHall commented on phalcon/Http/RequestInterface.zep
> +	 * @return string
Same goes here

2019-08-31 00:15 UTC, scrnjakovic commented
@sergeyklay @CameronHall hopefully everything is ok now

2019-09-09 03:56 UTC, CameronHall approved these changes

2019-09-09 09:42 UTC, sergeyklay commented
@niden What do you this PR?

2019-09-09 13:20 UTC, niden commented
This looks good. Thank you @scrnjakovic

2019-09-09 13:20 UTC, niden approved these changes

2019-09-09 13:20 UTC, merged