Fix exception message
phalcon/cphalcon pull request #14344
Opened 2019-09-01 19:00 UTC by Jeckerson

Hello!

* Type: code quality

2019-09-01 19:15 UTC, ruudboon submitted a review, later dismissed

2019-09-01 19:15 UTC, ruudboon commented
Thnx

2019-09-02 05:50 UTC, sergeyklay requested changes

2019-09-02 05:50 UTC, sergeyklay commented on phalcon/Session/Adapter/Stream.zep
> +            throw new Exception("The savePath [" . path . "] is not writeable");
```suggestion
            throw new Exception("The session save path [" . path . "] is not writable");
```

2019-09-02 12:40 UTC, sergeyklay approved these changes

2019-09-02 12:41 UTC, merged

2019-09-02 12:41 UTC, sergeyklay commented
Thank you