Create instance
phalcon/cphalcon pull request #14419
Opened 2019-09-25 21:53 UTC by niden

Hello!

* Type: performance
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Changed all calls to `new <object>` to use the `create_instance` or `create_instance_params` for better performance. 

Thanks

2019-09-25 21:54 UTC, niden commented
cc @sergeyklay @ruudboon

2019-09-26 04:50 UTC, ruudboon requested changes

2019-09-26 04:50 UTC, ruudboon commented on build/README.md
> +Please, refer to [Phalcon Internals documentation](https://internals.phalcon.io)
This domain does not exist. Redirect to docs?

2019-09-26 16:09 UTC, sergeyklay submitted a review, later dismissed

2019-09-26 16:11 UTC, sergeyklay commented on phalcon/Mvc/Model.zep
> +                create_instance_params(
@niden Can you return this back

2019-09-26 16:11 UTC, sergeyklay commented on phalcon/Logger/LoggerFactory.zep
> +        return create_instance_params(
And this (and similar)

2019-09-26 16:22 UTC, sergeyklay commented on build/README.md
> +Please, refer to [PHP's step by step guide](https://wiki.php.net/internals/windows/stepbystepbuild)
👍

2019-09-26 17:01 UTC, ruudboon approved these changes

2019-09-26 18:03 UTC, merged