update backers
phalcon/cphalcon pull request #14454
Opened 2019-10-06 22:34 UTC by Arhell

Hello!

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Thanks

2019-10-07 06:00 UTC, ruudboon submitted a review, later dismissed

2019-10-07 17:56 UTC, sergeyklay requested changes
I wouldn't like to to merge this to the master branch. Is there any real reason why this shouldn't be merged into 4.0.x instead of master?

2019-10-07 18:33 UTC, Arhell commented
Changed to 4 branch

2019-10-07 22:11 UTC, sergeyklay approved these changes

2019-10-08 05:38 UTC, Jeckerson approved these changes

2019-10-08 05:50 UTC, ruudboon approved these changes

2019-10-08 05:50 UTC, merged

2019-10-08 05:51 UTC, ruudboon commented
@Arhell thank you