T14464 cast on arr collection
phalcon/cphalcon pull request #14465
Opened 2019-10-12 19:20 UTC by niden

Hello!

* Type: enhancement
* Link to issue: #14464 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [x] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Added `cast` parameter to `Phalcon\Collection::get` and `Phalcon\Helper\Arr::get` allowing developers to cast the result returned to the type they want to.

Thanks

2019-10-12 19:21 UTC, niden commented
cc @ruudboon @sergeyklay

2019-10-13 10:45 UTC, ruudboon requested changes

2019-10-13 10:45 UTC, ruudboon commented on phalcon/Helper/Arr.zep
> +        if unlikely isset casts[cast] {
Shouldn't we throw an Exception when the cast value doesn't exist in the array?

2019-10-13 14:26 UTC, sergeyklay submitted a review, later dismissed

2019-10-13 17:40 UTC, niden commented
@ruudboon `settype` will return a notice if the wrong type is passed so we are OK on that.

2019-10-13 22:40 UTC, merged