Upgraded to Zephir 0.12.10
phalcon/cphalcon pull request #14479
Opened 2019-10-20 11:03 UTC by ruudboon

Hello!

* Type:  code quality 
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Upgrade to Zephir 0.12.10

2019-10-20 11:39 UTC, Jeckerson submitted a review, later dismissed

2019-10-20 19:18 UTC, sergeyklay requested changes

2019-10-20 19:18 UTC, sergeyklay commented on appveyor.yml
> +  ZEPHIR_VERSION: 0.12.10
@ruudboon Could you please update this
```diff
-   C:\php\php.exe -d error_reporting=32765 zephir.phar generate --backend=ZendEngine3 -Wnonexistent-function -Wnonexistent-class -Wunused-variable
+   C:\php\php.exe -d zephir.phar generate --backend=ZendEngine3 -Wnonexistent-function -Wnonexistent-class -Wunused-variable

2019-10-21 10:45 UTC, ruudboon commented on appveyor.yml
> +  ZEPHIR_VERSION: 0.12.10
@sergeyklay Fixed

2019-10-21 14:00 UTC, merged