Added missing method decrement in Phalcon\Helper\Str
phalcon/cphalcon pull request #14601
Opened 2019-12-08 15:32 UTC by ruudboon

Hello!

* Type: bug fix
* Link to issue: #14599

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:
Added missing method

2019-12-08 16:25 UTC, Jeckerson commented
You could unify all tests with `dataProvider()` method.

Example - https://codeception.com/docs/07-AdvancedUsage#DataProvider-Annotations

2019-12-08 20:18 UTC, niden approved these changes

2019-12-08 20:21 UTC, niden requested changes

2019-12-08 20:21 UTC, niden commented on phalcon/Helper/Str.zep
> +    final public static function decrement(string text, string separator = "_") -> string
Can you move this method to be after `decapitalize`. Keeping alphabetical sorting for methods.

2019-12-08 22:41 UTC, merged

2019-12-09 05:59 UTC, ruudboon commented
> You could unify all tests with `dataProvider()` method.
> 
> Example - https://codeception.com/docs/07-AdvancedUsage#DataProvider-Annotations

Yeah good idea. I just copied the increment test.