T14723 mbstring
phalcon/cphalcon pull request #14732
Opened 2020-01-17 23:30 UTC by niden

Hello!

* Type: bug fix
* Link to issue: #14723 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Changed methods internally to use `mbstring` equivalent ones (`strtolower`, etc.) making `mbstring` a prerequisite

Thanks

2020-01-18 02:57 UTC, CameronHall approved these changes

2020-01-18 06:19 UTC, sergeyklay commented
Please add mbstring to the list of the required extension https://github.com/phalcon/cphalcon/blob/ef31ca8fdfdcbaeef24bd93a32107a43b6c1ba6b/config.json#L17-L26

2020-01-18 06:26 UTC, sergeyklay requested changes

2020-01-18 06:26 UTC, sergeyklay commented on phalcon/Config/ConfigFactory.zep
> +        let adapter = mb_strtolower(config["adapter"]),
Is there any reason to use multi byte function for the adapter name? Do we plan provide support for PHP non in ASCII? AFAIK, mbstring functions are slower. So, it is curious to me, what we offer for such the price? Adapter names in national encodings?

2020-01-18 06:31 UTC, sergeyklay commented on phalcon/Config/ConfigFactory.zep
> +        let adapter = mb_strtolower(config["adapter"]),
I don't mind paying where it is necessary. But I don't quite understand why I should always pay for what I don't use.

2020-02-05 23:02 UTC, niden commented
Closing this. We need to run more tests since this impacts performance especially in the HTTP layer

2020-02-05 23:02 UTC, closed without merging