Fix session issue 14694
phalcon/cphalcon pull request #14759
Opened 2020-01-22 18:32 UTC by ruudboon

Hello!

* Type: bug fix 
* Link to issue: #14694

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [x] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:
During writing we lock the file and during reading we wait for the file to be unlocked.

2020-01-22 19:36 UTC, niden requested changes
Minor comment. If tests pass ci-skip the change and this is ready to merge

2020-01-22 19:36 UTC, niden commented on phalcon/Session/Adapter/Stream.zep
> +            if(flock(pointer, LOCK_SH)) {
Can you please put a space after `if` here?

2020-01-22 19:36 UTC, niden commented on phalcon/Storage/Adapter/Stream.zep
> +        if(flock(pointer, LOCK_SH)) {
Same

2020-01-23 20:41 UTC, Jeckerson submitted a review, later dismissed

2020-01-23 22:24 UTC, niden approved these changes

2020-01-23 22:25 UTC, merged