T14783 integration suite rework
phalcon/cphalcon pull request #14803
Opened 2020-02-01 18:17 UTC by niden

Hello!

* Type: enhancement - tests
* Link to issue: #14779 

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Created `database` suite to be run with `--env mysql` parameter against the target RDBMS
Kept integration tests where they are unless they access the database
Moved potential db tests in a `tocheck` folder so that we can slowly work and enable them.
Suite runs `sqlite` and `mysql` tests. `pgsql` suite needs work (tables are not created? not sure for now)

Thanks

2020-02-02 17:22 UTC, ruudboon requested changes

2020-02-02 17:22 UTC, ruudboon commented on CHANGELOG-4.0.md
> +- Added a way to utilize GitHub actions to run database tests against each RDBMS and reworked the testing suite. [#14779](https://github.com/phalcon/cphalcon/issues/14779)
I didn't add any comments about our Codeception 4 upgrade. Maybe we should add that here as well.

2020-02-02 17:22 UTC, ruudboon commented on tests/README.md
> +php tests/_ci/generage-db-schemas.php
Can you codecept build here as well.
And maybe we should prefix it with vendor/bin/codecept

2020-02-02 17:22 UTC, ruudboon commented on tests/_config/bootstrap.php
> +//loadEnvironment($root);
Do we still need this in comments. We can clean it up if you ask me. We can always look back in git. Goes for this whole file

2020-02-02 17:22 UTC, ruudboon commented on tests/README.md
>  ```
Can we add some documentation how the new migration models work and how you can add new tables etc.

2020-02-02 17:22 UTC, ruudboon commented
Few lines of feedback. But in general great work @niden

2020-02-02 19:50 UTC, niden commented
@ruudboon I will check those tonight maybe tomorrow. I have a bit more refactoring to do with the services of the DiTrait and this would be done

2020-02-03 21:22 UTC, ruudboon approved these changes

2020-02-03 22:12 UTC, merged