Test ManyToMany with multiple schemas
phalcon/cphalcon pull request #14854
Opened 2020-02-15 21:26 UTC by jenovateurs

Hello team!
I created a test for the PR #14716 .
I added new table in the schema.sql.
I added new models with different schema.
I fix an error in .env.exemple of nanobox.

* Type: code quality
* Link to issue: #14716

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [x] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Thanks

2020-02-15 21:31 UTC, ruudboon commented
@jenovateurs Thank you! I cancelled Appveyor to give priority to the release. I will restart it afterwards

2020-02-15 21:33 UTC, jenovateurs commented
@ruudboon No problem, thanks for the info ;-).

2020-02-15 21:36 UTC, Jeckerson commented
@jenovateurs Use fixtures migration classes instead of raw SQL.

Example here: `tests/_data/fixtures/Migrations/InvoicesMigration.php`

2020-02-15 21:40 UTC, jenovateurs commented
@Jeckerson No problem about fixtures migration. Should I delete my raw SQL in the schemas files ?

2020-02-15 21:58 UTC, ruudboon commented
@jenovateurs yes, you can delete the sql files you've added. We will move everything to the migrations soon. After that we can fully clean up.

2020-02-15 22:09 UTC, jenovateurs commented
What can I do about that: 

```
In Db.php line 278:
                                                                               
  Db: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied f  
  or user 'phalcon'@'%' to database 'hardware'                                 
  SQL query being executed:                                                    
  CREATE SCHEMA IF NOT EXISTS hardware  
```

2020-02-15 22:15 UTC, Jeckerson commented
@jenovateurs Did you rebased with 4.0.x?

2020-02-15 22:23 UTC, jenovateurs commented
@Jeckerson I've just rebased now but I still have the same issue.

2020-02-15 22:25 UTC, ruudboon commented
@jenovateurs I can have a look at it tomorrow. Must be something related to permissions on the github actions.

2020-02-15 22:30 UTC, jenovateurs commented
@ruudboon I think the problem is here : 
https://github.com/phalcon/cphalcon/blob/4.0.x/tests/_envs/pgsql.yml
In the database, I haven't got the permission to create a new schema.
I can create the new schema in the file environnement or add more privileges. 
We will see tomorrow, no problem ;-).

2020-02-15 23:32 UTC, niden commented
@jenovateurs If you have a better understanding and knowledge about Postgres make any necessary changes that are needed. 

Other than the area that you pointed regarding the schema creation, I think the rest of the database tests could run on postgres without major hitches (provided that the migrations are created)

2020-02-16 13:48 UTC, ruudboon commented
@jenovateurs Probably your latest commit will fail because you don't have permissions. 
To fix this we have a few options.
- Run tests as root
- Initialise permissions on starting of mysql/postgres containers.

Besides that I would like to use schema's that will be used for the full suite. This could be `hardware` but maybe we could go for something more general like `app` or `private` (we already have the `public` I think)

2020-02-16 14:01 UTC, ruudboon commented
Let’s run the suite as root for now. Looks like we need to extend the mysql and postgres containers otherwise. 
Can you change the example env and actions env to use the root user?

2020-02-16 14:35 UTC, ruudboon requested changes

2020-02-16 14:35 UTC, ruudboon commented on .github/workflows/codecoverage.yml
> +	  DATA_MYSQL_USER: root
Can indent this?

2020-02-16 14:35 UTC, ruudboon commented on tests/_data/assets/db/schemas/mysql_schema.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Please end files with a new line

2020-02-16 14:35 UTC, ruudboon commented on tests/_data/assets/db/schemas/postgresql_schema_nanobox.sql
> +--
same

2020-02-16 14:53 UTC, ruudboon commented on .github/workflows/codecoverage.yml
> +	        DATA_MYSQL_USER: root
I think there is a tab here. Please use spaces only.

2020-02-16 15:21 UTC, ruudboon submitted a review, later dismissed

2020-02-16 16:10 UTC, jenovateurs commented
It's the sqlite test that trigger the error. Because I haven't the SQL script. I don't know if it's possible to create a schema with sqlite.

2020-02-16 16:19 UTC, jenovateurs commented
I skiped sqlite for this special test so if you have another idea... I'm all ears (or eyes) :-).

2020-02-16 16:39 UTC, ruudboon approved these changes

2020-02-16 16:39 UTC, merged

2020-02-16 18:57 UTC, niden commented
I wish I had seen this earlier. Nothing you did Jeremy but the goal is to move away from the Robots and related tables and use a more realistic schema such as invoices/customers/products etc. Also by doing this we ensure that we use only models we need and not throw one model/table here just for one test.

Great work nonetheless. Thank you for taking the initiative on this.

Also for the future if you do not want a test to run for a particular RDBMs you can use the `getDriver()` method from the database helper.