Remove underscore prefix in methods
phalcon/cphalcon pull request #14971
Opened 2020-05-01 22:04 UTC by Jeckerson

Hello!

* Type: new feature | code quality
* Link to issue:

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Removed underscores in protected and extendable (not final) methods to be PSR-12 compliant.

Thanks

2020-05-01 22:39 UTC, sergeyklay approved these changes

2020-05-02 07:23 UTC, sergeyklay commented
/cc @phalcon/core-team

2020-05-03 15:27 UTC, niden commented
We cannot do this now. It breaks backwards compatibility. If it was only private methods that would be fine but since it touches protected methods it will break applications that extend these classes and use those methods.

We can put a @todo on this for v5

2020-05-03 18:26 UTC, sergeyklay commented
Is there any place where we can start collect things for v5?

2020-05-31 19:11 UTC, niden requested changes
Lets make a small change here so that this can be merged safely without breaking BC. 

Leave the underscore named methods where they are. Copy each of those methods to new ones without the underscore. From the one with the underscore, call the other one without. The underscore named methods become proxy ones. Add a @todo or @deprecated in the docblock of the underscore one so that we can remove those in v5.

This way we do what we need but also keep BC

2020-06-08 20:28 UTC, ruudboon commented
@Jeckerson If you have time can you rebase and have look at the requested changes?

2020-06-12 19:45 UTC, ruudboon requested changes
Please add the BC methods

2020-06-14 10:09 UTC, Jeckerson commented
Will try to add it during today.

2020-06-14 12:15 UTC, ruudboon requested changes
I would like to suggest to implement to logic in the methods that are going to be in v5.
Now we are getting extra unnecessary look ups `groupResult()` calls `_groupResult()` and it will be easier when cleaning up the deprecated methods.

2020-06-15 14:31 UTC, sergeyklay requested changes

2020-06-15 14:31 UTC, sergeyklay commented on phalcon/Mvc/Model.zep
> +         return this->_doLowUpdate(metaData, connection, table);
Here and all other places: As a far as doLowUpdate used by default could you please invert this logic wrap doLowUpdate inside _doLowUpdate.

2020-06-18 04:11 UTC, ruudboon approved these changes

2020-06-18 11:22 UTC, sergeyklay approved these changes

2020-06-19 12:57 UTC, niden approved these changes

2020-06-19 13:00 UTC, merged

2020-08-04 15:06 UTC, zsilbi commented
I think this is going to break BC this way, because the logic is not quite right.

For example, if someone had custom a `_postSaveRelatedRecords()` implemented in their `Model` before, it's not going to be ever called by the `Model` itself, after a save because it will only call the new function (`postSaveRelatedRecords()`) instead. 

```php
namespace My;

class Model extends \Phalcon\Mvc\Model {
   /**
    * My custom _postSaveRelatedRecords implementation
    */
   protected function _postSaveRelatedRecords(AdapterInterface $connection, $related): bool {
      // This won't be ever called by Model

      return parent::_postSaveRelatedRecords($connection, $related);
   }
}
```

Following this example, this solution only applies to those, who originally had `Model::_postSaveRelatedRecords()` calls in their `Model` for some reason.


```php
namespace My;

class Model extends \Phalcon\Mvc\Model {
   /**
     * My custom function
     * 
     * @throws Exception
     * @throws Model\Exception
     */
    public function doSomething(): void
    {
        // This will work, thanks to the proxy function
        $this->_postSaveRelatedRecords(
            $this->getWriteConnection(),
            $this->dirtyRelated
        );
    }
}
```