#15077 - Fix findFirst() return type
phalcon/cphalcon pull request #15080
Opened 2020-06-09 10:04 UTC by Jeckerson

Hello!

* Type: bug fix  | code quality
* Link to issue: #15077

**In raising this pull request, I confirm the following:**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [x] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

2020-06-09 11:36 UTC, sergeyklay requested changes

2020-06-09 11:36 UTC, sergeyklay commented on phalcon/Mvc/Model.zep
> +    public static function findFirst(var parameters = null) -> <ModelInterface> | null
Please correct interface

2020-06-09 11:43 UTC, sergeyklay approved these changes
From design point of view I'm OK with this change. But I'm not sure about the target branch. Are we going to break backward compatibility in minor branch?

/сс @phalcon/core-team

2020-06-09 11:50 UTC, Jeckerson commented
The problem, is that this needed to be changed back in `4.0.0`.

2020-06-10 08:33 UTC, ruudboon commented
Why can't we keep it as null and update the docs?

2020-06-10 08:52 UTC, Jeckerson commented
The docs are already updated.

2020-06-10 09:19 UTC, ruudboon commented
Hmm now I see. We do break BC so if we approach it purely like that we should do it in v5. On the other hand I think it was intended to have it like this in v4 so you could see this as a bug that we need we need to fix and address it in v4.1

2020-06-12 19:42 UTC, ruudboon approved these changes
Technically it looks good to me. Let's wait for @niden before merging this one into 4.1.x

2020-06-19 13:02 UTC, niden approved these changes

2020-06-19 13:03 UTC, merged