5.0.x
phalcon/cphalcon pull request #15970
Opened 2022-05-24 12:34 UTC by ustmaestro

Hello!

* Type: new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/15919

**In raising this pull request, I confirm the following:**

- [ ] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [ ] I have checked that another pull request for this purpose does not exist
- [ ] I wrote some tests for this PR
- [ ] I have updated the relevant CHANGELOG
- [ ] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change:

Added support to class constants annotations

    class MyClass
    {
          /**
           * @Simple
           */
          const MY_CONST = "test";
    }
    
    
    use \Phalcon\Annotations\Adapter\Memory;
    use \Phalcon\Annotations\Reader;
    use \Phalcon\Annotations\Reflection;  
    
    // Reader now returns constants array list that have annotations in docblock comments
    $reader = new Reader();
    $data = $reader->parse(Test::class);
    var_dump($data);

    // Reflection has a new method for getting constants annotations
    $reflection = new Reflection($data);
    var_dump($reflection->getConstantsAnnotations());

    // Annotation adapters has 2 new methods for getting constants annotations
    $memory = new Memory();
    var_dump($memory->getConstants(Test::class));                  // returns array
    var_dump($memory->getConstant(Test::class, 'TEST2'));     // returns Collection

Thanks

2022-05-24 19:47 UTC, niden requested changes
Please update the interface as well with the two new methods. Also we need the CHANGELOG to be updated.


Great work!!

2022-05-24 19:47 UTC, niden commented on phalcon/Annotations/Reader.zep
> +            for constant in array_keys(constants) {
Add a variable and assign `array_keys(constants` to it.

2022-05-25 18:56 UTC, niden commented
@ustmaestro Just update the changelog and this is ready!!

2022-05-30 15:33 UTC, niden approved these changes

2022-05-30 15:33 UTC, merged

2022-05-30 15:34 UTC, niden commented
Thank you @ustmaestro !

2022-06-01 02:10 UTC, okool commented
Thank @ustmaestro