[#16606] - feat: added events and events manager to storage and cache classes
phalcon/cphalcon pull request #16607
Opened 2024-06-07 08:43 UTC by noone-silent

Hello!

* Type: new feature
* Link to issue: https://github.com/phalcon/cphalcon/issues/16606

**In raising this pull request, I confirm the following:**

- [X] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md)
- [X] I have checked that another pull request for this purpose does not exist
- [X] I wrote some tests for this PR
- [X] I have updated the relevant CHANGELOG
- [X] I have created a PR for the [documentation](https://github.com/phalcon/docs) about this change

Small description of change: See title

Thanks

2024-06-07 17:35 UTC, niden requested changes

2024-06-07 17:43 UTC, apoca approved these changes

2024-06-08 00:57 UTC, noone-silent commented on phalcon/Cache/AbstractCache.zep
> +        this->fire("cache:beforeDelete");
I made the requested changes.

2024-06-08 00:57 UTC, noone-silent commented on phalcon/Cache/AbstractCache.zep
> +        this->fire("cache:beforeDeleteMultiple");
Refactored

2024-06-08 00:59 UTC, niden approved these changes

2024-06-08 16:28 UTC, merged

2024-06-08 16:28 UTC, niden commented
Thank you @noone-silent